const frank_sinatra_songs = [
    [
        "Ac-cent-tchu-ate the Positive",
        "1950 (television)",
        "Harold Arlen, Johnny Mercer",
    ],
    ["Accidents Will Happen", "1950", "Johnny Burke, Jimmy Van Heusen"],
    ["Adeste Fideles", "1946, 1957", "John Francis Wade"],
    ["Ad-Lib Blues", "1954 (film)", "Yip Harburg, Burton Lane"],
    [
        "An Affair to Remember (Our Love Affair)",
        "1962",
        "Harold Adamson, Leo McCarey, Harry Warren",
    ],
    ["After You've Gone", "1984", "Henry Creamer, Turner Layton"],
    ["Ain't She Sweet", "1962", "Milton Ager, Jack Yellen"],
    [
        "Ain't Cha Ever Comin' Back?",
        "1947",
        "Axel Stordahl, Irving Taylor, Paul Weston",
    ],
    ["Air For English Horn", "1945", "Alec Wilder"],
    ["Alice Blue Gown", "1940 (radio)", "Joseph McCarthy, Harry Tierney"],
    ["All Alone", "1962", "Irving Berlin"],
    ["All By Myself", "1976", "Eric Carmen"],
    ["All I Do Is Dream of You", "1958", "Nacio Herb Brown, Arthur Freed"],
    ["All I Need is the Girl", "1967", "Stephen Sondheim, Jule Styne"],
    ["All My Tomorrows", "1958, 1969", "Sammy Cahn, Jimmy Van Heusen"],
    ["All of Me", "1946, 1947, 1954", "Gerald Marks, Seymour Simons"],
    ["All of You", "1979", "Cole Porter"],
    ["All or Nothing at All", "1939, 1961, 1966, 1977", "Arthur Altman, Jack Lawrence"],
    ["All the Things You Are", "1945", "Oscar Hammerstein II, Jerome Kern"],
    ["All the Way", "1957, 1963", "Sammy Cahn, Jimmy Van Heusen"],
    ["All the Way Home", "1983", "Teddy Randazzo"],
    ["All This and Heaven Too", "1940", "Eddie DeLange, Jimmy Van Heusen"],
    ["All Through the Day", "1946", "Oscar Hammerstein II, Jerome Kern"],
    ["Almost Like Being in Love", "1947, 1961", "Alan Jay Lerner, Frederick Loewe"],
    ["Always", "1946, 1947, 1960", "Irving Berlin"],
    ["America the Beautiful", "1945, 1963", "Samuel A. Ward"],
    ["American Beauty Rose", "1950, 1961", "Arthur Altman, Mack David, Redd Evans"],
    ["Among My Souvenirs", "1946, 1954", "Edgar Leslie, Lawrence Wright"],
    ["And Then You Kissed Me", "1944 (radio)", "Sammy Cahn, Jimmy Van Heusen[1]"],
    ["Angel Eyes", "1958, 1971, 1978", "Earl Brent, Matt Dennis"],
    ["Anything", "1940", "Eddie DeLange, P. Napoleon, Frank Signorelli"],
    ["Anything Goes", "1956", "Cole Porter"],
    ["Anytime (I'll Be There)", "1975", "Paul Anka"],
    ["Anytime, Anywhere", "1953", "Imogen Carpenter, Lenny Adelson"],
    ["Any Time at All", "1964", "Baker Knight"],
    ["April in Paris", "1950, 1957, 1961", "Vernon Duke, Yip Harburg"],
    ["April Played the Fiddle", "1940", "Johnny Burke, James Monaco"],
    ["Are You Lonesome Tonight?", "1962", "Lou Handman, Roy Turk"],
    ["Aren't You Glad You're You?", "1945", "Johnny Burke, Jimmy Van Heusen"],
    ["Around the World", "1957", "Harold Adamson, Victor Young"],
    ["As Long as I Live", "1960 (television)", "Harold Adamson, Ted Koehler"],
    ["As Time Goes By", "1961", "Herman Hupfeld"],
    ["As You Desire Me", "1961", "Allie Wrubel"],
    ["At Least a Little in Love", "1940", "unknown"],
    ["At Long Last Love", "1956, 1962", "Cole Porter"],
    ["Autumn in New York", "1947, 1957", "Vernon Duke"],
    ["Autumn Leaves", "1957", "Joseph Kosma, Johnny Mercer, Jacques Prévert"],
    ["Available", "1964", "Sammy Cahn, Ned Wynn, L. B. Marks"],
    ["Ave Maria", "1945", "Franz Schubert"],
    ["Azure-Te (Paris Blues)", "1952", "William Davis, Donald Wolf"],
    ["A Baby Just Like You", "1975", "John Denver, Joe Henry"],
    [
        "Baby, Won't You Please Come Home?",
        "1957",
        "Charles Warfield, Clarence Williams",
    ],
    ["Bad, Bad Leroy Brown", "1973, 1974 (live)", "Jim Croce"],
    ["Bali Ha'i", "1949", "Oscar Hammerstein II, Richard Rodgers"],
    ["Bang Bang (My Baby Shot Me Down)", "1973, 1981", "Sonny Bono"],
    ["Barbara", "1977", "Mack David, Jimmy Van Heusen"],
    ["Baubles, Bangles and Beads", "1958, 1967", "George Forrest, Robert Wright"],
    ["The Beautiful Strangers", "1969", "Rod McKuen"],
    ["Be Careful, It's My Heart", "1942, 1960", "Irving Berlin"],
    ["Before the Music Ends", "1979", "Gordon Jenkins"],
    ["Begin the Beguine", "1946", "Cole Porter"],
    ["Bein' Green", "1970", "Joe Raposo"],
    ["The Bells of Christmas", "1968", "Traditional"],
    ["The Best I Ever Had", "1976", "Danny Hice, Ruby Hice"],
    ["The Best is Yet to Come", "1964, 1994", "Cy Coleman, Carolyn Leigh"],
    ["The Best of Everything", "1984", "Fred Ebb, John Kander"],
    ["Between the Devil and the Deep Blue Sea", "1959", "Harold Arlen, Ted Koehler"],
    [
        "Bewitched, Bothered and Bewildered",
        "1957, 1963, 1994",
        "Lorenz Hart, Richard Rodgers",
    ],
    ["Bim Bam Baby", "1952", "Sammy Mysels"],
    [
        "The Birth of the Blues",
        "1952, 1957",
        "Buddy G. DeSylva, Lew Brown, Ray Henderson",
    ],
    ["Black", "1956", "Victor Young"],
    ["Blame It on My Youth", "1956", "Edward Heyman, Oscar Levant"],
    ["Blue", "1956", "Alec Wilder"],
    ["Blue Hawaii", "1957", "Ralph Rainger, Leo Robin"],
    ["Blue Lace", "1968", "Bill Jacob, Patty Jacob, Riz Ortolani"],
    ["Blue Moon", "1960", "Lorenz Hart, Richard Rodgers"],
    ["Blue Skies", "1941, 1946", "Irving Berlin"],
    ["Blues in the Night", "1958", "Harold Arlen, Johnny Mercer"],
    [
        "Body and Soul",
        "1947, 1984",
        "Edward Heyman, Robert Sour, Frank Eyton, Johnny Green",
    ],
    ["Bonita", "1969", "Antonio Carlos Jobim, Ray Gilbert, Gene Lees"],
    ["Bop Goes My Heart", "1948", "Walter Bishop Sr., Jule Styne"],
    ["Born Free", "1967", "John Barry, Don Black"],
    ["Both Sides Now", "1968", "Joni Mitchell"],
    ["The Boys Night Out", "1962", "Sammy Cahn, Jule Styne"],
    ["Brazil", "1957", "Ary Barroso, Bob Russell"],
    ["The Brooklyn Bridge", "1946", "Sammy Cahn, Jule Styne"],
    ["Brown", "1956", "Jeff Alexander"],
    ["Buds Won't Bud", "1940 (radio)", "Harold Arlen, Yip Harburg"],
    ["But Beautiful", "1947", "Johnny Burke, Jimmy Van Heusen"],
    ["But None Like You", "1947", "Ray Noble"],
    ["But Not for Me", "1979", "George Gershwin, Ira Gershwin."],
    ["By the Time I Get to Phoenix", "1968", "Jimmy Webb"],
    ["Bye Bye Baby", "1948", "Leo Robin, Jule Styne"],
    ["Bye Bye Blackbird", "1988 (live recording)", "Mort Dixon, Ray Henderson"],
    ["California", "1963", "Jimmy Van Heusen, Sammy Cahn"],
    ["Call Me", "1966", "Tony Hatch"],
    ["Call Me Irresponsible", "1963", "Jimmy Van Heusen, Sammy Cahn"],
    ["The Call of the Canyon", "1940", "Billy Hill"],
    ["Collegiate", "1957 (television)", "Nat Bonx, Moe Jaffe"],
    ["Can I Steal a Little Love?", "1956", "Phil Tuminello"],
    ["Can't We Be Friends", "1955", "Paul James, Kay Swift"],
    ["Can't You Just See Yourself?", "1947", "Sammy Cahn, Jule Styne"],
    ["Carolina in the Morning", "1963 (live recording)", "Walter Donaldson, Gus Kahn"],
    ["Castle Rock", "1951", "Ervin Drake, Al Sears, Jimmy Shirl"],
    ["Catana", "1947", "Eddie DeLange, Alfred Newman"],
    ["C'est Magnifique", "1959", "Cole Porter"],
    ["Change Partners", "1967", "Irving Berlin"],
    ["The Charm of You", "1944", "Sammy Cahn, Jule Styne"],
    ["Charmaine", "1962", "Lew Pollack, Erno Rapee"],
    ["Chattanoogie Shoe Shine Boy", "1950", "Harry Stone, Jack Stapp"],
    ["Cheek to Cheek", "1958", "Irving Berlin"],
    ["Cherry Pies Ought to Be You", "1950", "Cole Porter"],
    ["Chicago (That Toddlin' Town)", "1957", "Fred Fisher"],
    ["Christmas Dreaming", "1947", "Irving Gordon, Lester Lee"],
    ["Christmas Memories", "1975", "Alan Bergman, Marilyn Bergman, Don Costa"],
    ["The Christmas Song", "1957", "Mel Tormé, Bob Wells"],
    ["The Christmas Waltz", "1954, 1957, 1968", "Sammy Cahn, Jule Styne"],
    ["Ciribiribin", "1939", "Alberto Pestalozza, Carlo Tiochet"],
    ["Close Enough for Love", "1982", "Johnny Mandel, Paul Williams"],
    ["Close to You", "1943, 1956", "Jerry Livingston, Carl Lampl, Al Hoffman."],
    ["(They Long to Be) Close to You", "1970", "Burt Bacharach, Hal David"],
    ["The Coffee Song", "1946, 1960", "Bob Hilliard, Dick Miles"],
    ["Come Back to Me", "1967", "Burton Lane, Alan Jay Lerner"],
    [
        "Come Back to Sorrento",
        "1950",
        "Claude Aveling, Ernesto De Curtis, Giambattista De Curtis",
    ],
    ["Come Blow Your Horn", "1963", "Sammy Cahn, Jimmy Van Heusen"],
    ["Come Dance with Me", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    ["Come Fly with Me", "1957, 1965, 1994", "Sammy Cahn, Jimmy Van Heusen"],
    ["Come Out, Come Out, Wherever You Are", "1944", "Sammy Cahn, Jule Styne"],
    ["Come Rain or Come Shine", "1961, 1993", "Harold Arlen, Johnny Mercer"],
    ["Come Waltz with Me", "1962", "Sammy Cahn, Jule Styne"],
    [
        "Comme Ci Comme Ca",
        "1948",
        "Bruno Coquatrix, Pierre Dudan, Alex Kramer, Joan Whitney Kramer",
    ],
    ["The Continental", "1950, 1964", "Con Conrad, Herb Magidson"],
    ["A Cottage for Sale", "1959", "Larry Conley, Willard Robison"],
    ["Could 'Ja?", "1946", "Bill Carey, Carl T. Fischer"],
    ["Crazy Love", "1957", "Sammy Cahn, Phil Tuminello"],
    ["The Cradle Song", "1944", "Johannes Brahms"],
    ["Cuddle up a Little Closer, Lovey Mine", "1958", "Otto Harbach, Karl Hoschna"],
    ["The Curse of an Aching Heart", "1961", "Henry Fink, Al Piantadosi"],
    ["Cycles", "1968", "Gayle Caldwell"],
    ["Dancing in the Dark", "1958", "Arthur Schwartz, Howard Dietz"],
    ["Dancing on the Ceiling", "1955", "Lorenz Hart, Richard Rodgers"],
    ["The Day After Forever", "1946", "Johnny Burke, Jimmy Van Heusen"],
    ["Day by Day", "1945, 1961", "Axel Stordahl, Sammy Cahn, Paul Weston"],
    ["Day In, Day Out", "1953, 1954, 1958", "Rube Bloom, Johnny Mercer"],
    [
        "Manhã De Carnaval (A Day in the Life of a Fool)",
        "1969",
        "Luiz Bonfá, Antônio Maria.",
    ],
    ["The Days of Wine and Roses", "1964", "Henry Mancini, Johnny Mercer"],
    ["Daybreak", "1942, 1961", "Harold Adamson, Ferde Grofe"],
    ["Dear Heart", "1964", "Ray Evans, Jay Livingston, Henry Mancini"],
    ["Dear Little Boy of Mine", "1950", "Ernest Ball, J. Keirn Brennan"],
    ["Deep in a Dream", "1955", "Eddie DeLange, Jimmy Van Heusen"],
    ["Deep Night", "1951", "Rudy Vallee, Charlie Henderson"],
    [
        "Desafinado",
        "1969",
        "Antonio Carlos Jobim, Newton Mendonça, Jon Hendricks, Gene Lees",
    ],
    ["Devil May Care", "1940", "Johnny Burke, Harry Warren"],
    [
        "Dick Haymes, Dick Todd and Como",
        "1944",
        "Johnny Burke, Sammy Cahn, Jimmy Van Heusen",
    ],
    ["Didn't We", "1969", "Jimmy Webb"],
    ["Dig Down Deep", "1942", "Walter Hirsch, S. Marco, Gerald Marks"],
    ["Dindi", "1967", "Antonio Carlos Jobim, Ray Gilbert, Aloysio de Oliveira"],
    ["Do I Worry?", "1941", "Bobby Worth, Stanley Cowan"],
    ["Do You Know Why?", "1940", "Johnny Burke, Jimmy Van Heusen"],
    ["Dolores", "1941", "Frank Loesser, Louis Alter"],
    ["Don'cha Go 'Way Mad", "1962", "Illinois Jacquet, Jimmy Mundy, Al Stillman."],
    ["Don't Be a Do-Badder", "1964", "Sammy Cahn, Jimmy Van Heusen"],
    ["Don't Be that Way", "1961", "Benny Goodman, Mitchell Parish, Edgar Sampson"],
    ["Don't Blame Me", "1953", "Dorothy Fields, Jimmy McHugh"],
    ["Don't Change Your Mind About Me", "1954", "Lenny Adelson, Imogen Carpenter"],
    ["Don't Cry, Joe", "1949, 1961", "Joe Marsala"],
    ["Don't Ever Be Afraid to Go Home", "1952", "Bob Hilliard, Carl Sigman"],
    [
        "Don't Ever Go Away (Por Causa de Você)",
        "1969",
        "Ray Gilbert, Delores Duran, Antonio Carlos Jobim",
    ],
    ["Don't Forget Tonight, Tomorrow", "1945", "Jay Milton, Ukie Sherin"],
    [
        "Don't Get Around Much Anymore",
        "1965 (television)",
        "Duke Ellington, Bob Russell",
    ],
    ["Don't Like Goodbyes", "1956", "Harold Arlen, Truman Capote"],
    ["Don't Make a Beggar of Me", "1953", "Al Sherman"],
    ["Don't Sleep in the Subway", "1967", "Tony Hatch, Jackie Trent"],
    ["Don't Take Your Love From Me", "1961", "Henry Nemo"],
    ["Don't Wait Too Long", "1965", "Sunny Skylar"],
    ["Don't Worry 'Bout Me", "1953", "Rube Bloom, Ted Koehler."],
    ["Down Where the Trade Winds Play", "1942 (radio)", "unknown"],
    ["Downtown", "1966", "Tony Hatch"],
    ["Dream", "1945, 1960", "Johnny Mercer"],
    ["Dream a Little Dream of Me", "1958", "Fabian Andre, Gus Kahn, Wilbur Schwandt"],
    ["Dream Away", "1973", "Paul Williams, John Williams"],
    ["Drinking Again", "1967", "Johnny Mercer, Doris Tauber."],
    ["Dry Your Eyes", "1976", "Neil Diamond, Robbie Robertson"],
    ["The Dum Dot Song (I Put a Penny in the Gum Slot)", "1946", "Julian Kay"],
    ["Early American", "1964", "Johnny Burke, Jimmy Van Heusen"],
    ["East of the Sun (and West of the Moon)", "1940, 1961", "Brooks Bowman"],
    ["Ebb Tide", "1958", "Robert Maxwell, Carl Sigman"],
    ["Elizabeth", "1969", "Bob Gaudio, Jake Holmes"],
    ["Embraceable You", "1944, 1960, 1994", "George Gershwin, Ira Gershwin"],
    [
        "Emily (Theme from The Americanization of Emily)",
        "1964, 1977",
        "John Mandel, Johnny Mercer",
    ],
    ["Empty Is (spoken)", "1969", "Rod McKuen"],
    ["Empty Tables", "1973, 1974, 1976", "Johnny Mercer, Jimmy Van Heusen"],
    ["The End of a Love Affair", "1956", "Edward C. Redding"],
    [
        "Evergreen (Love Theme from A Star Is Born)",
        "1976",
        "Barbra Streisand, Paul Williams",
    ],
    ["Ever Homeward", "1947", "Sammy Cahn, Jule Styne"],
    ["Every Day of My Life", "1939", "M. Beck, B. Hays, Harry James"],
    ["Every Man Should Marry", "1949", "Benny Davis, Abner Silver"],
    [
        "Everybody Has the Right to Be Wrong (At Least Once)",
        "1965",
        "Sammy Cahn, Jimmy Van Heusen",
    ],
    ["Everybody Loves Somebody", "1947, 1957", "Sam Coslow, Irving Taylor, Ken Lane"],
    ["Everybody Ought to Be in Love", "1977", "Paul Anka"],
    ["Everybody's Twistin'", "1962", "Rube Bloom, Ted Koehler"],
    ["Everything Happens to Me", "1941, 1956, 1974, 1981", "Tom Adair, Matt Dennis"],
    ["Exactly Like You", "1946, 1949", "Dorothy Fields, Jimmy McHugh"],
    ["Exodus", "1962", "Ernest Gold"],
    ["The Fable of the Rose", "1940", "Josef Myrow, Bickley Reichner"],
    ["Fairy Tale", "1955", "Jerry Livingston, Dok Stanford"],
    ["Faithful", "1951", "Mary Ann Kennedy, Candy Parton, Pam Rose"],
    ["Falling In Love with Love", "1945, 1961", "Lorenz Hart, Richard Rodgers"],
    ["Farewell, Farewell to Love", "1951", "George Siravo, Jack Wolf"],
    ["Feelin' Kinda Sunday", "1970", "Nino Tempo, Annette Tucker, Kathleen Wakefield"],
    ["Feet of Clay", "1952", "Alex Kramer, Joan Whitney Kramer, Hy Zaret"],
    ["A Fella With An Umbrella", "1948", "Irving Berlin"],
    ["A Fellow Needs a Girl", "1947", "Oscar Hammerstein II, Richard Rodgers"],
    ["A Fine Romance", "1960", "Dorothy Fields, Jerome Kern"],
    ["The First Noël", "1957", "Traditional"],
    ["Five Hundred Guys", "1956", "David Cantor, Irving Kosloff"],
    ["Five Minutes More", "1946, 1961", "Sammy Cahn, Jule Styne"],
    ["Flowers Mean Forgiveness", "1956", "Al Frisch, Edward R. White, Mack Wolfson"],
    ["Fly Me to the Moon", "1964", "Bart Howard"],
    ["A Foggy Day", "1953, 1960, 1994", "George Gershwin, Ira Gershwin"],
    ["Follow Me", "1967", "Alan Jay Lerner, Frederick Loewe"],
    [
        "Fools Rush In (Where Angels Fear to Tread)",
        "1940, 1947, 1960",
        "Rube Bloom, Johnny Mercer",
    ],
    ["For a While", "1969", "Bob Gaudio, Jake Holmes"],
    ["For Every Man There's a Woman", "1947", "Harold Arlen, Leo Robin"],
    ["For Once in My Life", "1969, 1994", "Ron Miller, Orlando Murden"],
    ["For the Good Times", "1979", "Kris Kristofferson"],
    ["Forget Domani", "1965", "Norman Newell, Riz Ortolani"],
    ["Forget to Remember", "1969", "Victoria Pike, Teddy Randazzo"],
    ["A Friend of Yours", "1945", "Johnny Burke, Jimmy Van Heusen"],
    ["Free for All", "1941", "Tom Adair, Matt Dennis"],
    ["French Foreign Legion", "1958", "Aaron Schroeder, Guy Wood"],
    ["Frenesi", "1941 (radio)", "Ray Charles, Alberto Domínguez, Bob Russell"],
    ["From Here to Eternity", "1953", "Fred Karger, Robert Wells"],
    ["From Promise to Promise", "1969", "Rod McKuen"],
    ["From the Bottom of My Heart", "1939", "Roy Ingraham, Jack Murray"],
    ["From the Bottom to the Top", "1955", "Gee Wilson"],
    [
        "From This Day Forward",
        "1946",
        "Robert Bernard, Mort Greene, Leigh Harline, Jan Wiley",
    ],
    ["From This Moment On", "1956", "Cole Porter"],
    ["Fugue for Tinhorns", "1963", "Frank Loesser"],
    ["Full Moon and Empty Arms", "1945", "Buddy Kaye, Ted Mossman"],
    ["The Future", "1979", "Gordon Jenkins"],
    ["The Gal that Got Away", "1954, 1981", "Harold Arlen, Ira Gershwin"],
    ["The Game is Over", "1970", "John Denver"],
    ["A Garden in the Rain", "1962", "Carroll Gibbons, James Dyrenforth"],
    ["Gentle on My Mind", "1968", "John Hartford"],
    ["Get Happy", "1954", "Harold Arlen, Ted Koehler"],
    ["Get Me to the Church on Time", "1966", "Alan Jay Lerner, Frederick Loewe"],
    [
        "The Girl from Ipanema",
        "1967",
        "Vinícius de Moraes, Norman Gimbel, Antônio Carlos Jobim",
    ],
    ["The Girl Next Door", "1953, 1962", "Hugh Martin, Ralph Blane"],
    ["The Girl That I Marry", "1946", "Irving Berlin"],
    ["The Girls I Never Kissed", "1986, 1988", "Jerry Leiber, Mike Stoller"],
    ["Give Her Love", "1966", "Jim Harbert"],
    ["Glad to Be Unhappy", "1955", "Lorenz Hart, Richard Rodgers"],
    ["Go Tell it on the Mountain", "1964", "Traditional"],
    ["God's Country", "1950", "Haven Gillespie, Beasley Smith"],
    ["Goin' Out of My Head", "1969", "Teddy Randazzo, Bobby Weinstein"],
    ["Gold", "1956", "Nelson Riddle"],
    ["Golden Moment", "1965", "Kenny Jacobson, Rhoda Roberts"],
    ["The Good Life", "1964", "Sacha Distel, Jack Reardon"],
    ["A Good Man is Hard to Find", "1951", "Eddie Green"],
    ["Gone with the Wind", "1958", "Allie Wrubel, Herb Magidson"],
    ["Good Thing Going", "1981", "Stephen Sondheim"],
    ["Goodbye", "1958", "Gordon Jenkins"],
    ["Goodbye Lover, Goodbye", "1969", "unknown"],
    ["Goodbye (She Quietly Says)", "1969", "Bob Gaudio, Jake Holmes"],
    ["Goodnight Irene", "1950", "Traditional"],
    ["Goodnight My Love", "1958", "Mack Gordon, Harry Revel"],
    [
        "Goodnight Sweetheart",
        "1958",
        "Ray Noble, Jimmy Campbell and Reg Connelly, Rudy Vallee",
    ],
    ["Goody Goody", "1962", "Matty Malneck, Johnny Mercer."],
    ["Gotta Be This or That", "1945 (radio)", "Sunny Skylar"],
    ["Granada", "1961", "Agustín Lara"],
    ["Gray", "1956", "Alec Wilder"],
    ["Green", "1956", "Gordon Jenkins"],
    [
        "Guess I'll Hang My Tears Out to Dry",
        "1946, 1958, 1993",
        "Sammy Cahn, Jule Styne",
    ],
    ["Gunga Din", "1966", "Jim Croce, Rudyard Kipling"],
    ["Guys and Dolls", "1963", "Frank Loesser"],
    ["The Gypsy", "1962", "Billy Reid"],
    ["Half as Lovely (Twice as True)", "1954", "Sammy Gallop, Lew Spence"],
    ["Half Way Down the Street", "1940 (radio)", "unknown"],
    ["Hallelujah, I Love Her So", "1969", "Ray Charles"],
    ["Happy Birthday to You", "1994 (live performance)", "Patty Hill, Mildred J. Hill"],
    ["Hark the Herald Angels Sing", "1957", "Traditional"],
    ["Have You Met Miss Jones?", "1960, 1961", "Lorenz Hart, Richard Rodgers"],
    [
        "Have Yourself a Merry Little Christmas",
        "1947, 1957, 1963",
        "Ralph Blane, Hugh Martin",
    ],
    ["He's My Guy", "1957", "Gene DePaul, Don Raye"],
    ["Head on My Pillow", "1940", "Pierre Connor, Bissel Palmer"],
    [
        "Hear My Song Violetta",
        "1940",
        "Buddy Bernier, Robert Emmerich, Othmar Klase, Rudolph Inkesch",
    ],
    ["Hello, Dolly!", "1964", "Jerry Herman"],
    [
        "Hello, Young Lovers",
        "1951, 1954, 1965",
        "Oscar Hammerstein II, Richard Rodgers",
    ],
    ["Help Yourself to My Heart", "1947", "Buddy Kaye, Sammy Timberg"],
    ["Here Comes the Night", "1939", "H. Edelstein, C. Hohengarten, Frank Loesser"],
    ["Here Goes", "1958", "Sammy Cahn"],
    ["Here's That Rainy Day", "1959", "Johnny Burke, Jimmy Van Heusen"],
    ["Here's to Love", "1941 (radio)", "Mina Anna Arenson"],
    ["Here's to the Band", "1983", "Sharman Howe, Alfred Nittoli, Artie Schroeck"],
    ["Here's to the Losers", "1963", "Robert Wells, Jack Segal"],
    ["Hey! Jealous Lover", "1956", "Sammy Cahn, Kay Twomey, Bee Walker"],
    ["Hey Look, No Crying", "1981", "Susan Birkenhead, Jule Styne"],
    ["Hidden Persuasion", "1960", "Wainwright Churchill III"],
    ["High Hopes", "1959", "Sammy Cahn, Jimmy Van Heusen"],
    ["Hit the Road to Dreamland", "1958", "Harold Arlen, Johnny Mercer"],
    ["Home on the Range", "1946", "Brewster M. Higley, Daniel E. Kelley"],
    ["Homesick That's All", "1945", "Gordon Jenkins"],
    ["Hooray for Love", "1982", "Harold Arlen, Leo Robin"],
    ["The House I Live In", "1945, 1964, 1994", "Lewis Allan, Earl Robinson"],
    ["How About You?", "1941, 1956", "Burton Lane, Ralph Freed"],
    ["How Am I to Know", "1940 (radio)", "Jack King, Dorothy Parker"],
    ["How Are You Fixed for Love?", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    ["How Could You Do a Thing Like That to Me?", "1955", "Tyree Glenn, Allan Roberts"],
    ["How Cute Can You Be?", "1946", "Bill Carey, Carl T. Fischer"],
    ["How Deep is the Ocean?", "1946, 1960", "Irving Berlin"],
    ["How Do You Do Without Me?", "1941", "Joe Bushkin, John DeVries"],
    [
        "How Do You Keep the Music Playing?",
        "1983, 1984, 1994",
        "Alan Bergman, Marilyn Bergman, Michel Legrand",
    ],
    ["How High the Moon", "1967 (television)", "Nancy Hamilton, Morgan Lewis"],
    [
        "How Insensitive",
        "1967",
        "Antônio Carlos Jobim, Norman Gimbel, Vinícius de Moraes",
    ],
    [
        "(How Little It Matters) How Little We Know",
        "1956, 1963",
        "Carolyn Leigh, Phil Springers",
    ],
    ["How Old am I?", "1965", "Gordon Jenkins"],
    ["A Hundred Years from Today", "1984", "Victor Young, Ned Washington, Joe Young"],
    ["The Hucklebuck", "1949", "Roy Alfred, A. Gibson"],
    ["The Hurt Doesn't Go Away", "1973", "Joe Raposo"],
    ["Hush-A-Bye-Island", "1946", "Harold Adamson, Jimmy McHugh"],
    ["I Am Loved", "1950", "Cole Porter"],
    ["I Begged Her", "1944", "Sammy Cahn, Jule Styne"],
    ["I Believe", "1946, 1957", "Sammy Cahn, Jule Styne"],
    ["I Believe I'm Gonna Love You", "1975", "Harry Lloyd, Gloria Skleroy"],
    ["I Believe In You", "1964", "Frank Loesser"],
    ["I Can Read Between the Lines", "1953", "Sid Frank, Ramon M Getzov"],
    ["I Can't Believe I'm Losing You", "1964", "Don Costa, Phil Zeller"],
    [
        "I Can't Believe That You're In Love With Me",
        "1960",
        "Clarence Gaskill, Jimmy McHugh",
    ],
    ["I Can't Get Started", "1959", "Vernon Duke Ira Gershwin"],
    [
        "I Can't Give You Anything But Love",
        "1959 (live recording), 1959 (television)",
        "Dorothy Fields, Jimmy McHugh",
    ],
    ["I Can't Stop Loving You", "1964", "Don Gibson"],
    ["I Concentrate on You", "1947, 1960, 1967", "Cole Porter"],
    ["I Could Have Danced All Night", "1958", "Alan Jay Lerner, Frederick Loewe"],
    ["I Could Have Told You", "1953", "Carl Sigman, Jimmy Van Heusen"],
    ["I Could Make You Care", "1940", "Sammy Cahn, Saul Chaplin"],
    ["I Could Write a Book", "1952, 1957", "Lorenz Hart, Richard Rodgers"],
    ["I Couldn't Care Less", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    [
        "I Couldn't Sleep a Wink Last Night",
        "1943, 1956",
        "Harold Adamson, Jimmy McHugh",
    ],
    ["I Cover the Waterfront", "1957", "Johnny Green, Edward Heyman"],
    ["I Didn't Know What Time It Was", "1957", "Lorenz Hart, Richard Rodgers"],
    ["I Don't Know Why (I Just Do)", "1945", "Fred E. Ahlert, Roy Turk"],
    [
        "I Don't Stand a Ghost of a Chance with You",
        "1945, 1959",
        "Victor Young, Ned Washington, Bing Crosby",
    ],
    ["I Dream of You", "1944", "Marjorie Goetschius, Edna Osser"],
    ["I Fall in Love Too Easily", "1944", "Sammy Cahn, Jule Styne"],
    ["I Fall in Love With You Ev’ryday", "1946", "Sam H. Stept"],
    ["I Get a Kick Out of You", "1953, 1962", "Cole Porter"],
    [
        "I Get Along Without You Very Well (Except Sometimes)",
        "1955",
        "Hoagy Carmichael",
    ],
    ["I Give You My Word", "1941 (radio)", "Al Kavelin, Lyn"],
    [
        "I Got a Gal I Love (In North And South Dakota)",
        "1946",
        "Sammy Cahn, Jimmy Van Heusen",
    ],
    [
        "(I Got A Woman Crazy For Me) She's Funny That Way",
        "1943-8",
        "Neil Moret, Richard A. Whiting",
    ],
    [
        "I Got It Bad (And That Ain't Good)",
        "1956",
        "Duke Ellington, Paul Francis Webster",
    ],
    [
        "I Got Plenty o' Nuttin'",
        "1956",
        "George Gershwin, Ira Gershwin, DuBose Heyward",
    ],
    ["I Gotta Right to Sing the Blues", "1962", "Harold Arlen, Ted Koehler"],
    ["I Guess I'll Have to Change My Plan", "1956", "Howard Dietz, Arthur Schwartz"],
    [
        "I Guess I'll Have to Dream the Rest",
        "1941, 1950",
        "Martin Block, Bud Green, Mickey Stoner",
    ],
    ["I Had the Craziest Dream", "1979", "Mack Gordon, Harry Warren"],
    ["I Hadn't Anyone Till You", "1961", "Ray Noble"],
    ["I Have But One Heart", "1945", "Johnny Farrow, Marty Symes"],
    [
        "I Have Dreamed 	1963 	Oscar Hammerstein II, Richard Rodgers, I Haven't Time to Be a Millionaire",
        "1940",
        "Johnny Burke, James Monaco",
    ],
    [
        "I Hear a Rhapsody",
        "1952",
        "George Fragos, Jack Baker, Dick Gasparre, Richard Bard",
    ],
    ["I Heard the Bells on Christmas Day", "1964", "John D Marks"],
    ["I Left My Heart in San Francisco", "1962", "George Cory, Douglass Cross"],
    ["I Like the Sunrise", "1967", "Duke Ellington"],
    ["I Like to Lead When I Dance", "1964", "Sammy Cahn, Jimmy Van Heusen"],
    ["I Love My Wife", "1976", "Cy Coleman, Michael Stewart"],
    ["I Love Paris", "1959, 1960", "Cole Porter"],
    ["I Love You", "1946, 1953, 1962", "Cole Porter"],
    ["I Love You", "1953", "Harry Archer, Harlan Thompson"],
    ["I Love You", "1946", "George Forest, Robert Wright"],
    ["I Loved Her", "1981", "Gordon Jenkins"],
    [
        "I May Be Wrong (But I Think You're Wonderful)",
        "1958 (television)",
        "Harry Ruskin, Henry Sullivan",
    ],
    ["I Never Knew", "1961", "Ted Fio Rito, Gus Kahn"],
    ["I Only Have Eyes for You", "1945, 1962", "Al Dubin, Harry Warren"],
    ["I Saw Your Face in a Cloud", "1940 (radio)", "Robert Fetters"],
    ["I See It Now", "1965", "William Engvick, Alec Wilder"],
    ["I See Your Face Before Me", "1955", "Howard Dietz, Arthur Schwartz"],
    ["I Should Care", "1945", "Sammy Cahn, Axel Stordahl, Paul Weston"],
    ["I Sing the Songs", "1976", "Bruce Johnston"],
    ["I Think of You", "1941, 1957", "Jack Elliott, Don Marcotte"],
    ["I Thought About You", "1955, 1956", "Johnny Mercer, Jimmy Van Heusen"],
    ["I Tried", "1941", "Clark Dennis, Paul Hand, Carl Nutter"],
    ["I Wanna Be Around", "1964", "Johnny Mercer, Sadie Vimmerstedt"],
    ["I Want to Thank Your Folks", "1946", "Bennie Benjamin, George David Weiss"],
    ["I Went Down to Virginia", "1947", "David Mann, Redd Evans"],
    ["I Whistle a Happy Tune", "1951", "Oscar Hammerstein II, Richard Rodgers"],
    ["I Will Drink the Wine", "1970", "Paul Ryan"],
    ["I Will Wait for You", "1966", "Marc Demy, Norman Gimbel, Michel Legrand"],
    ["I Wish I Were in Love Again", "1956", "Lorenz Hart, Richard Rodgers"],
    ["I Wish You Love", "1964", "Léo Chauliac, Charles Trenet, Albert A. Beach"],
    ["I Wished on the Moon", "1965", "Dorothy Parker, Ralph Rainger"],
    ["I Won't Dance", "1956, 1962", "Oscar Hammerstein II, Otto Harbach, Jerome Kern"],
    ["I Would Be In Love (Anyway)", "1969", "Bob Gaudio, Jake Holmes"],
    ["I Wouldn't Trade Christmas", "1968", "Sammy Cahn, Jimmy Van Heusen"],
    ["I'd Know You Anywhere", "1940", "Johnny Mercer, Jimmy McHugh"],
    ["Ida, Sweet As Apple Cider", "1941 (radio)", "Eddie Leonard, Eddie Munson"],
    ["If", "1974", "David Gates"],
    ["If Ever I Would Leave You", "1962", "Alan Jay Lerner, Frederick Loewe"],
    ["If I Ever Love Again", "1949", "Russ Carlyle, Dick Reynolds"],
    ["If I Forget You", "1947", "Irving Caesar"],
    ["If I Had Three Wishes", "1955", "Claude Baum, Lew Spence"],
    [
        "If I Had You",
        "1947, 1956, 1962",
        "Jimmy Campbell and Reg Connelly, Ted Shapiro",
    ],
    ["If I Loved You", "1945", "Oscar Hammerstein II, Richard Rodgers"],
    ["If I Only Had a Match", "1947", "Arthur Johnston, George W. Meyer, Lee Morris"],
    ["If I Should Lose You", "1984", "Ralph Rainger, Leo Robin"],
    ["If I Steal a Kiss", "1947", "Nacio Herb Brown, Edward Heyman"],
    ["If It's the Last Thing I Do", "1956", "Sammy Cahn, Saul Chaplin"],
    ["If Loveliness Were Music", "1944", "Bert Reisfeld, Mickey Stoner"],
    ["If Only She'd Look My Way", "1950", "Alan Melville, Ivor Novello"],
    ["If This Isn't Love", "1954 (film)", "Yip Harburg, Burton Lane"],
    ["If You Are But a Dream", "1944, 1957", "Nat Bonx, Jack Fulton, Moe Jaffe"],
    ["If You Never Come to Me", "1967", "Ray Gilbert, Antonio Carlos Jobim"],
    ["If You Go Away", "1969", "Jacques Brel, Rod McKuen"],
    [
        "If You Never Come to Me",
        "1967",
        "Ray Gilbert, Antonio Carlos Jobim, Aloysio de Oliveria",
    ],
    ["If You Please", "1943", "Johnny Burke, Jimmy Van Heusen"],
    ["If You Stub Your Toe on the Moon", "1949", "Johnny Burke, Jimmy Van Heusen"],
    ["I'll Be Around", "1955", "Alec Wilder"],
    ["I'll Be Home for Christmas", "1957", "Kim Gannon, Walter Kent, Buck Ram"],
    ["I'll Be Seeing You", "1940, 1961, 1961", "Sammy Fain, Irving Kahal"],
    ["I'll Follow My Secret Heart", "1962", "Noël Coward"],
    ["I'll Make Up for Everything", "1947", "Ross Parker"],
    ["I'll Never Be The Same", "1955", "Gus Kahn, Matty Malneck, Frank Signorelli"],
    ["I'll Never Let a Day Pass By", "1941", "Frank Loesser, Victor Schertzinger"],
    ["I'll Never Smile Again", "1940, 1959, 1965", "Ruth Lowe"],
    ["I'll Only Miss Her When I Think of Her", "1965", "Sammy Cahn, Jimmy Van Heusen"],
    ["I'll Remember April", "1961", "Gene de Paul, Patricia Johnston, Don Raye"],
    ["I'll See You Again", "1961", "Noël Coward"],
    ["I'll See You in My Dreams", "1940 (radio)", "Isham Jones, Gus Kahn"],
    ["I'll Take Tallulah", "1942", "Yip Harburg, Burton Lane"],
    ["Ill Wind", "1955", "Harold Arlen, Ted Koehler"],
    ["I'm a Fool to Want You", "1951, 1957", "Joel Herron, Frank Sinatra, Jack Wolf"],
    [
        "I'm Beginning to See the Light",
        "1962",
        "Duke Ellington, Don George, Johnny Hodges, Harry James",
    ],
    ["I'm Getting Sentimental Over You", "1961", "George Bassman, Ned Washington"],
    ["I'm Glad There Is You", "1947", "Jimmy Dorsey, Paul Madeira"],
    ["I'm Gonna Live Till I Die", "1954", "Manny Curtis, Al Hoffman, Walter Kent"],
    ["I'm Gonna Make It All the Way", "1973", "Floyd Huddleston"],
    [
        "I'm Gonna Sit Right Down and Write Myself a Letter",
        "1954, 1962",
        "Fred E. Ahlert, Joe Young",
    ],
    ["I'm in the Mood for Love", "1942 (radio)", "Dorothy Fields, Jimmy McHugh"],
    ["I'm Not Afraid", "1970", "Jacques Brel, Gérard Jouannest, Rod McKuen"],
    ["I'm Sorry I Made You Cry", "1946", "N.J. Clesi"],
    ["I'm Walking Behind You", "1953", "Billy Reid"],
    ["Imagination", "1940, 1961", "Johnny Burke, Jimmy Van Heusen"],
    ["The Impatient Years", "1955", "Sammy Cahn, Jimmy Van Heusen"],
    ["The Impossible Dream", "1966", "Joe Darion, Mitch Leigh"],
    ["In the Blue of Evening", "1942, 1961", "Tom Adair, Alfonso D'Artega"],
    [
        "In the Cool, Cool, Cool of the Evening",
        "1964",
        "Hoagy Carmichael, Johnny Mercer",
    ],
    ["In the Shadow of the Moon", "1969", "Earl Brown, Heinz Keissling"],
    ["In the Still of the Night", "1960", "Cole Porter"],
    ["In the Wee Small Hours of the Morning", "1955, 1963", "Bob Hilliard, David Mann"],
    ["Indian Summer", "1967", "Al Dubin, Victor Herbert"],
    ["Indescreet", "1962", "Sammy Cahn, Jimmy Van Heusen"],
    ["Innamorata", "1957 (television)", "Jack Brooks, Harry Warren"],
    ["Is There a Chance for Me?", "1940", "William Granzow"],
    ["Isle of Capri", "1957", "Wilhelm Grosz, Jimmy Kennedy"],
    ["Isn't She Lovely?", "1979", "Stevie Wonder"],
    ["It All Came True", "1947", "Sunny Skylar"],
    [
        "It All Comes Back to Me Now",
        "1941",
        "Alex Kramer, Joan Whitney Kramer, Hy Zaret",
    ],
    [
        "It All Depends on You",
        "1949, 1958, 1960",
        "Buddy G. DeSylva, Lew Brown, Ray Henderson",
    ],
    [
        "It Came Upon a Midnight Clear",
        "1947, 1957",
        "Edmund Sears, Richard Storrs Willis",
    ],
    ["It Came to Me", "1940", "Louis DePyro"],
    ["It Could Happen to You", "1956", "Johnny Burke, Jimmy Van Heusen"],
    ["It Gets Lonely Early", "1965", "Sammy Cahn, Jimmy Van Heusen"],
    ["It Had to Be You", "1963, 1979", "Isham Jones, Gus Kahn"],
    ["It Happened in Monterey", "1956", "Billy Rose, Mabel Wayne"],
    ["It Happens Every Spring", "1949", "Mack David, Josef Myrow"],
    [
        "It Might as Well Be Spring",
        "1961, 1964",
        "Oscar Hammerstein II, Richard Rodgers",
    ],
    ["It Never Entered My Mind", "1947, 1955, 1981", "Lorenz Hart, Richard Rodgers"],
    ["It Only Happens When I Dance With You", "1948", "Irving Berlin"],
    ["It Started All Over Again", "1942, 1961", "Bill Carey, Carl T. Fischer"],
    ["It Was a Very Good Year", "1965, 1966 (live[2])", "Ervin Drake"],
    ["It Worries Me", "1954", "Fritz Schulz-Reichel, Carl Sigman, Ernst Verch"],
    ["It's a Blue World", "1961", "Bob Wright, Chet Forrest"],
    ["It's a Lonesome Old Town", "1958", "Charles Kisco, Harry Tobias"],
    [
        "It's a Long Way (From Your House to My House)",
        "1951",
        "Roy C. Bennett, Sid Tepper",
    ],
    ["It's a Lovely Day Tomorrow", "1940", "Irving Berlin"],
    ["It's a Wonderful World", "1961", "Harold Adamson, Jan Savitt, Johnny Watson"],
    ["It's All So New to Me", "1941 (radio)", "Pearl Black"],
    ["It's All Right With Me", "1959, 1984", "Cole Porter"],
    ["It's All Up to You", "1946", "Sammy Cahn, Jule Styne"],
    ["It's Always You", "1940, 1961", "Johnny Burke, Jimmy Van Heusen)"],
    ["It's Been a Long, Long Time", "1945", "Sammy Cahn, Jule Styne"],
    ["It's Easy to Remember", "1956", "Lorenz Hart, Richard Rodgers"],
    ["It's Funny to Everyone but Me", "1939", "Jack Lawrence"],
    ["It's Nice to Go Trav'ling", "1957", "Sammy Cahn, Jimmy Van Heusen"],
    ["It's Only a Paper Moon", "1950, 1960", "Harold Arlen, Yip Harburg, Billy Rose"],
    ["It's Only Money", "1951", "Sammy Cahn, Jule Styne"],
    ["It's Over, It's Over, It's Over", "1960", "Matt Dennis, Don Stanford"],
    ["It's Sunday", "1983", "Susan Birkenhead, Jule Styne"],
    ["It's the Same Old Dream", "1946, 1957", "Sammy Cahn, Jule Styne"],
    ["I've Been There", "1979", "Gordon Jenkins"],
    ["I've Been to Town", "1969", "Rod McKuen"],
    ["I've Got a Crush on You", "1947, 1960, 1993", "George Gershwin, Ira Gershwin."],
    ["I've Got a Home in That Rock", "1945", "Traditional"],
    ["I've Got a Restless Spell", "1940 (radio)", "Nancy Lampe"],
    ["I've Got My Eyes on You", "1940", "Cole Porter"],
    ["I've Got My Love to Keep Me Warm", "1960", "Irving Berlin"],
    ["I've Got the World on a String", "1953, 1993", "Harold Arlen, Ted Koehler"],
    ["I've Got You Under My Skin", "1956, 1963, 1993", "Cole Porter"],
    ["I've Grown Accustomed to Her Face", "1962", "Alan Jay Lerner, Frederick Loewe"],
    ["I've Had My Moments", "1956", "Walter Donaldson, Gus Kahn"],
    ["I've Heard That Song Before", "1961", "Sammy Cahn, Jule Styne"],
    ["I've Lost My Heart Again", "1940", "Leo Robin"],
    ["I've Never Been in Love Before", "1963", "Frank Loesser"],
    ["Jeepers Creepers", "1954", "Johnny Mercer, Harry Warren"],
    ["Jesus is a Rock (In a Weary Land)", "1945", "Traditional"],
    ["Jingle Bells", "1946, 1957", "James Lord Pierpont"],
    ["June in January", "1942 (radio)", "Ralph Rainger, Leo Robin"],
    ["Just an Old Stone House", "1945", "Alec Wilder"],
    ["Just as Though You Were Here", "1942, 1974", "John Benson Brooks, Eddie DeLange"],
    ["Just Close Your Eyes", "1943-8", "John M. Elliot, Sam Mineo, Lewis Rodgers"],
    ["Just for Now", "1947", "Dick Redmond"],
    ["Just Friends", "1959", "Sam M. Lewis, John Klenner"],
    ["Just in Time", "1958", "Betty Comden, Adolph Green, Jule Styne"],
    ["Just One of Those Things", "1954, 1961 (live[3])", "Cole Porter"],
    ["(Just One Way to Say) I Love You", "1949", "Irving Berlin"],
    ["Just the Way You Are", "1979", "Billy Joel"],
    ["Killing Me Softly", "1973", "Charles Fox"],
    ["Kiss Me Again", "1944", "Victor Herbert, Henry Martyn Blossom"],
    ["Kisses and Tears", "1949, 1950", "Sammy Cahn, Jule Styne"],
    [
        "L.A. Is My Lady",
        "1984",
        "Alan Bergman, Marilyn Bergman, Quincy Jones, Peggy Lipton",
    ],
    ["Là ci darem la mano", "1946", "Lorenzo Da Ponte, Wolfgang Amadeus Mozart"],
    ["Lady Day", "1969", "Bob Gaudio, Jake Holmes"],
    ["The Lady from Twentynine Palms", "1939", "Allie Wrubel"],
    ["The Lady Is a Tramp", "1956, 1993", "Lorenz Hart, Richard Rodgers"],
    ["The Lamp Is Low", "1939", "Peter DeRose, Mitchell Parish, Maurice Ravel"],
    ["The Lamplighter's Serenade", "1942", "Hoagy Carmichael, Paul Francis Webster"],
    ["The Last Call for Love", "1942", "Yip Harburg, Burton Lane, M. Cummings"],
    ["The Last Dance", "1958, 1960", "Sammy Cahn, Jimmy Van Heusen"],
    ["Last Night When We Were Young", "1954, 1965", "Harold Arlen, Yip Harburg"],
    ["Laura", "1947, 1957", "Johnny Mercer, David Raksin"],
    ["Lean Baby", "1953", "Roy Alfred, Billy May"],
    ["Learn to Croon", "1940 (radio)", "Sam Coslow, Arthur Johnston"],
    ["Learnin' the Blues", "1955, 1962", "Dolores Vicki Silvers"],
    ["Leave It All to Me", "1988", "Paul Anka"],
    ["Leaving on a Jet Plane", "1970", "John Denver"],
    ["Let It Snow! Let It Snow! Let It Snow!", "1950", "Sammy Cahn, Jule Styne"],
    ["Let Me Love You Tonight", "1943-8", "Mitchell Parish, René Touzet"],
    [
        "Let Me Try Again",
        "1973",
        "Paul Anka, Sammy Cahn, Romvald Figuier, Michel Jourdan, Caravelli",
    ],
    ["Let There Be Love", "1962 (television)", "Ian Grant, Lionel Rand"],
    ["Let Us Break Bread Together", "1964", "Roy Ringwald"],
    ["Let's Do It, Let's Fall in Love", "1959", "Cole Porter"],
    ["Let's Face the Music and Dance", "1960, 1979", "Irving Berlin"],
    ["Let's Fall in Love", "1960", "Harold Arlen, Ted Koehler"],
    ["Let's Get Away from It All", "1941, 1957", "Tom Adair, Matt Dennis"],
    ["Let's Put Out the Lights (and Go to Sleep)", "1958", "Herman Hupfeld"],
    ["Let's Start the New Year Right", "1943", "Irving Berlin"],
    ["Let's Take An Old-Fashioned Walk", "1949", "Irving Berlin"],
    ["Life is So Peculiar", "1950", "Johnny Burke, Jimmy Van Heusen"],
    ["Life's a Trippy Thing", "1970", "Howard Greenfield, Linda Laurie"],
    ["Light a Candle in the Chapel", "1942", "Duke Leonard, Ed G. Nelson, Harry Pease"],
    ["Like a Sad Song", "1976", "John Denver"],
    ["Like Someone in Love", "1953", "Johnny Burke, Jimmy Van Heusen"],
    ["Lilly Belle", "1945", "Dave Franklin, Irving Taylor"],
    ["Linda", "1977", "Jack Lawrence"],
    [
        "The Little Drummer Boy",
        "1964",
        "Katherine Kennicott Davis, Henry Onorati, Harry Simeone",
    ],
    ["Little Girl Blue", "1953", "Lorenz Hart, Richard Rodgers"],
    ["Little Green Apples", "1968", "Bobby Russell"],
    ["A Little Learning is a Dangerous Thing", "1947", "D. Jacobs, Sy Oliver"],
    ["London by Night", "1950, 1957, 1962", "Carroll Coates"],
    ["Lonely Town", "1957", "Leonard Bernstein, Betty Comden, Adolph Green"],
    ["Lonesome Cities", "1969", "Rod McKuen"],
    ["The Lonesome Road", "1956", "Gene Austin, Nathaniel Shilkret"],
    ["Long Ago (And Far Away)", "1943-8", "Ira Gershwin, Jerome Kern"],
    ["A Long Night", "1981", "Loonis McGlohon, Alec Wilder"],
    ["The Look of Love", "1962", "Sammy Cahn, Jimmy Van Heusen"],
    ["Look Out for Jimmy Valentine", "1967 (television)", "Gus Edwards, Edward Madden"],
    ["Look to Your Heart", "1955", "Sammy Cahn, Jimmy Van Heusen"],
    [
        "Looking at the World Thru Rose Colored Glasses",
        "1962",
        "Tommie Malie, Jimmy Steiger",
    ],
    ["Looking for Yesterday", "1940", "Eddie DeLange, Jimmy Van Heusen"],
    ["The Lord's Prayer", "1949", "Albert Hay Malotte"],
    ["Lost in the Stars", "1946, 1963", "Maxwell Anderson, Kurt Weill"],
    ["Love and Marriage", "1955, 1965", "Sammy Cahn, Jimmy Van Heusen"],
    ["Love Is a Many-Splendored Thing", "1964", "Sammy Fain, Paul Francis Webster"],
    ["Love Is Here to Stay", "1955", "George Gershwin, Ira Gershwin"],
    ["Love Is Just Around the Corner", "1962", "Lewis E. Gensler, Leo Robin"],
    ["(Love Is) The Tender Trap", "1955, 1962", "Sammy Cahn, Jimmy Van Heusen"],
    ["Love Isn't Just for the Young", "1963", "Bernard Knee, Herbert L. Miller"],
    ["Love Lies", "1940", "Ralph Freed, Joseph Meyer, Carl Sigman"],
    ["Love Locked Out", "1956", "Max Kester, Ray Noble"],
    ["Love Looks So Well On You", "1959", "Alan Bergman, Marilyn Bergman, Lew Spence"],
    ["Love Makes Us Whatever We Want to Be", "1982", "Sammy Cahn, Jule Styne"],
    ["Love Me", "1951", "Ned Washington, Victor Young"],
    ["Love Me as I Am", "1941", "Frank Loesser, Louis Alter"],
    ["Love Me Tender", "1979", "Elvis Presley, Vera Matson"],
    ["Love Means Love", "1950", "Bonnie Lake, Carl Sigman"],
    ["Love Walked In", "1961", "George Gershwin, Ira Gershwin"],
    ["A Lovely Way to Spend an Evening", "1943", "Harold Adamson, Jimmy McHugh"],
    ["Lover", "1950, 1961", "Lorenz Hart, Richard Rodgers"],
    [
        "A Lover Is Blue 	1940 	Charles Carpenter, Jimmy Mundy, James Oliver Young, Love's Been Good to Me",
        "1969",
        "Rod McKuen",
    ],
    ["Luck Be a Lady", "1963, 1994", "Frank Loesser"],
    [
        "Luna Rossa (Blushing Moon)",
        "1952",
        "Vincenzo de Crescenzo, Renato Matassa, Antonio Viscione, Kermit Goell",
    ],
    ["Lush Life", "1958", "Billy Strayhorn"],
    ["MacArthur Park", "1979", "Jimmy Webb"],
    ["Mack the Knife", "1984, 1986, 1994", "Bertolt Brecht, Kurt Weill"],
    ["Mad About You", "1949", "Ned Washington, Victor Young"],
    ["Makin' Whoopee", "1956", "Walter Donaldson, Gus Kahn"],
    ["Mama Will Bark", "1951", "Dick Manning"],
    ["Mam'selle", "1947, 1960", "Mack Gordon, Edmund Goulding"],
    ["A Man Alone", "1969", "Rod McKuen"],
    ["The Man I Love", "1957", "George Gershwin, Ira Gershwin"],
    ["The Man in the Looking Glass", "1965", "Bart Howard"],
    ["Maria", "1962", "Leonard Bernstein, Stephen Sondheim"],
    ["Marie", "1940 (radio)", "Irving Berlin"],
    ["Maybe This Time", "1995", "Fred Ebb, John Kander"],
    ["Maybe You'll Be There", "1957", "Rube Bloom, Sammy Gallop"],
    ["Me and My Shadow", "1962", "Dave Dreyer, Al Jolson, Billy Rose"],
    ["Mean to Me", "1947", "Fred E. Ahlert, Roy Turk"],
    ["Meditation", "1967", "Antonio Carlos Jobim, Norman Gimbel, Newton Mendonça"],
    ["Meet Me at the Copa", "1950", "Sammy Cahn, Axel Stordahl"],
    [
        "Meet Me Tonight in Dreamland",
        "1954 (radio)",
        "Leo Friedman, Beth Slater Whitson",
    ],
    ["Melancholy Mood", "1939", "William Schumann, V. Knight"],
    ["Melody of Love", "1954", "Hans Engelmann, Tom Glazer"],
    [
        "Memories Are Made of This",
        "1957 (television), 1988 (live recording)",
        "Richard Dehr, Terry Gilkyson, Frank Miller",
    ],
    ["Memories of You", "1956, 1961", "Eubie Blake, Andy Razaf"],
    ["Merry Christmas Little Angel", "1975", "unknown"],
    ["Michael and Peter", "1969", "Bob Gaudio, Jake Holmes"],
    ["Mighty Lak' a Rose", "1945", "Ethelbert Nevin., Frank Lebby Stanton"],
    ["A Million Dreams Ago", "1961", "Eddie Howard, Dick Jurgens, Lew Quadling"],
    ["Mind if I Make Love to You?", "1956", "Cole Porter"],
    ["Mister Booze", "1964", "Sammy Cahn, Jimmy Van Heusen"],
    ["Mistletoe and Holly", "1957", "Hank Sanicola, Frank Sinatra, Doc Stanford"],
    ["Misty", "1961", "Johnny Burke, Erroll Garner"],
    ["Moment to Moment", "1965", "Henry Mancini, Johnny Mercer"],
    [
        "Moments in the Moonlight",
        "1940",
        "Richard Himber, Irving Gordon, Alvin Kaufman",
    ],
    ["Monday Morning Quarterback", "1981", "Don Costa, Pamela Phillips-Oland"],
    ["Monique", "1958", "Elmer Bernstein, Sammy Cahn"],
    ["Montmartre, Montmartre", "1959", "Cole Porter"],
    ["Mood Indigo", "1955", "Barney Bigard, Duke Ellington, Irving Mills"],
    ["Moody River", "1968", "Gary Bruce"],
    ["The Moon Got in My Eyes", "1965", "Johnny Burke, Arthur Johnston"],
    ["Moon Love", "1965", "Mack David, André Kostelanetz"],
    ["Moon River", "1964", "Henry Mancini, Johnny Mercer"],
    ["Moon Song", "1965", "Sam Coslow, Arthur Johnston"],
    ["The Moon Was Yellow", "1945, 1958, 1965", "Fred E. Ahlert, Edgar Leslie"],
    ["The Moon Won't Talk", "1941 (radio)", "unknown"],
    ["Moonlight Becomes You", "1965", "Johnny Burke, Jimmy Van Heusen"],
    ["Moonlight in Vermont", "1957, 1994", "John Blackburn, Karl Suessdorf"],
    ["Moonlight Mood", "1965", "Harold Adamson, Peter DeRose"],
    ["Moonlight on the Ganges", "1961", "Sherman Myers, Chester Wallace"],
    ["Moonlight Serenade", "1965", "Glenn Miller, Mitchell Parish"],
    ["More", "1964", "Nino Oliviero, Riz Ortolani"],
    ["The More I See You", "1983", "Mack Gordon, Harry Warren"],
    ["More Than You Know", "1979", "Edward Eliscu, Vincent Youmans, Billy Rose"],
    ["The Most Beautiful Girl In The World", "1966", "Lorenz Hart, Richard Rodgers"],
    ["Mr. Success", "1958", "Edwin Grienes, Hank Sanicola, Frank Sinatra"],
    ["Mrs. Robinson", "1969", "Paul Simon"],
    ["The Music Stopped", "1943, 1946, 1947", "Harold Adamson, Jimmy McHugh"],
    ["My Baby Just Cares for Me", "1966", "Walter Donaldson, Gus Kahn"],
    ["My Blue Heaven", "1950, 1960", "Walter Donaldson, George A. Whiting"],
    ["My Buddy", "1939", "Walter Donaldson, Gus Kahn"],
    ["My Cousin Louella", "1947", "Bernard Bierman, Jack Manus"],
    ["My First Edition", "1941", "Carol Bailey"],
    ["My Foolish Heart", "1988", "Ned Washington, Victor Young"],
    ["My Funny Valentine", "1953, 1994", "Lorenz Hart, Richard Rodgers"],
    ["My Girl", "1952", "Charles Freed"],
    ["My Heart Stood Still", "1963", "Lorenz Hart, Richard Rodgers"],
    ["My Kind of Girl", "1962", "Leslie Bricusse"],
    [
        "My Kind of Town (Chicago Is)",
        "1964, 1966 (live[4]), 1974 (live[5]), 1994",
        "Sammy Cahn, Jimmy Van Heusen",
    ],
    ["My Love for You", "1947", "Abner Silver, Sid Wayne"],
    ["My Memoirs", "1941 (radio)", "Ferguson, Greenough"],
    ["My Melancholy Baby", "1945", "Ernie Burnett, George A. Norton"],
    ["My One and Only Love", "1953", "Robert Mellin, Guy Wood"],
    ["My Romance", "1946, 1947", "Lorenz Hart, Richard Rodgers"],
    ["My Shawl", "1945", "Stanley Adams, Xavier Cugat"],
    ["My Shining Hour", "1979", "Harold Arlen, Johnny Mercer"],
    ["My Silent Love", "1942", "Edward Heyman, Isham Jones, Dana Suesse"],
    ["My Sweet Lady", "1970", "John Denver"],
    ["My Way", "1969, 1994", "Paul Anka, Claude François, Jacques Revaux"],
    ["My Way Of Life", "1968", "Bert Kaempfert, Herbert Rehbein, Carl Sigman"],
    ["Name It and It's Yours", "1961", "Sammy Cahn, Jimmy Van Heusen"],
    [
        "Nancy (With the Laughing Face)",
        "1944, 1945, 1963, 1977",
        "Phil Silvers, Jimmy Van Heusen",
    ],
    ["Nature Boy", "1948", "Eden Ahbez"],
    ["The Nearness of You", "1947, 1960", "Hoagy Carmichael, Ned Washington"],
    ["Necessity", "1954 (film)", "Yip Harburg, Burton Lane"],
    ["Neiani", "1941", "Sy Oliver, Axel Stordahl"],
    ["New York, New York", "1979", "Fred Ebb, John Kander"],
    ["Nevertheless (I'm in Love with You)", "1950, 1960", "Bert Kalmar, Harry Ruby"],
    ["Nice 'n' Easy", "1960", "Alan Bergman, Marilyn Bergman, Lew Spence"],
    ["Nice Work if You Can Get It", "1956, 1962", "George Gershwin, Ira Gershwin"],
    ["Night (spoken)", "1969", "Rod McKuen"],
    ["Night After Night", "1949", "Sammy Cahn, Axel Stordahl, Paul Weston"],
    ["Night and Day", "1942, 1947, 1956, 1961, 1977", "Cole Porter"],
    [
        "The Night Is Young and You're So Beautiful",
        "1945",
        "Irving Kahal, Billy Rose, Dana Suesse",
    ],
    ["The Night We Called it a Day", "1942, 1947, 1957", "Tom Adair, Matt Dennis"],
    [
        "A Nightingale Sang in Berkeley Square",
        "1962",
        "Eric Maschwitz, Manning Sherwin",
    ],
    ["No One Ever Tells You", "1956", "Hub Atwood, Carroll Coates"],
    ["No Orchids for My Lady", "1948", "Jack Strachey, Alan Stranks"],
    ["Noah", "1973", "Joe Raposo"],
    ["Nobody Wins", "1973", "Kris Kristofferson"],
    ["None But the Lonely Heart", "1946, 1947, 1959", "Pëtr Il´ic Cajkovskij"],
    ["Not as a Stranger", "1955", "Buddy Kaye, Jimmy Van Heusen"],
    ["Not So Long Ago", "1940", "Clay A. Boland, Bickley Reichner"],
    ["Nothing But the Best", "1962", "Johnny Rotella"],
    ["Nothing in Common", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    ["Now Is the Hour", "1962", "Maewa Kaihau, Clement Scott, Dorothy Stewart."],
    ["O Little Town of Bethlehem", "1947, 1957", "Phillips Brooks, Lewis Redner"],
    ["Ode to Billie Joe", "1967 (television)", "Bobbie Gentry"],
    ["Oh Bess, Oh Where's My Bess?", "1946", "George Gershwin, DuBose Heyward"],
    ["Oh, Babe, What Would You Say?", "1975", "Eileen Sylvia Smith"],
    ["Oh How I Miss You Tonight", "1962", "Benny Davis, Joe Burke, Mark Fisher."],
    ["Oh Marie", "1957 (television), 1988 (live recording)", "Eduardo Di Capua"],
    ["Oh! Look at Me Now", "1941, 1956", "Joe Bushkin, John DeVries"],
    ["Oh, What a Beautiful Mornin'", "1943", "Oscar Hammerstein II, Richard Rodgers"],
    [
        "Oh! What It Seemed to Be",
        "1945, 1963",
        "Bennie Benjamin, Frankie Carle, George David Weiss",
    ],
    ["Oh, You Crazy Moon", "1965", "Johnny Burke, Jimmy Van Heusen"],
    ["Old MacDonald Had a Farm", "1960", "Traditional"],
    ["Ol' Man River", "1944, 1963", "Oscar Hammerstein II, Jerome Kern"],
    ["Old Devil Moon", "1956, 1963", "Yip Harburg, Burton Lane"],
    ["An Old Fashioned Christmas", "1964", "Sammy Cahn, Jimmy Van Heusen"],
    ["The Old Master Painter", "1949", "Haven Gillespie, Beasley Smith"],
    ["Old School Teacher", "1945", "Willard Robison"],
    [
        "The Oldest Established (Permanent Floating Crap Game in New York)",
        "1963",
        "Frank Loesser",
    ],
    ["On a Clear Day (You Can See Forever)", "1966", "Burton Lane, Alan Jay Lerner"],
    ["On a Little Street in Singapore", "1939", "Billy Hill, Peter DeRose"],
    ["On the Road to Mandalay", "1957", "Rudyard Kipling, Oley Speaks"],
    ["On the Sunny Side of the Street", "1961", "Dorothy Fields, Jimmy McHugh"],
    ["Once I Loved", "1967", "Ray Gilbert, Antonio Carlos Jobim, Vinicius de Moraes"],
    ["Once in a While", "1940", "Michael Edwards, Bud Green"],
    ["Once in Love with Amy", "1948", "Frank Loesser"],
    ["(Once Upon a) Moonlight Night", "1946", "Irving Bibo, Sidney Clare"],
    ["Once Upon a Time", "1965", "Lee Adams, Charles Strouse"],
    ["One Finger Melody", "1950", "Kermit Goell, Al Hoffman, Fred Spielman"],
    [
        "One for My Baby (and One More for the Road)",
        "1947, 1958, 1993",
        "Harold Arlen, Johnny Mercer",
    ],
    [
        "The One I Love (Belongs to Somebody Else)",
        "1940, 1959, 1961",
        "Isham Jones, Gus Kahn",
    ],
    ["One Love", "1946", "Leo Robin, David Rose"],
    ["One Note Samba", "1969", "Antonio Carlos Jobim, Newton Mendonça"],
    ["One Red Rose", "1941 (radio)", "Willard Moyle"],
    ["The Only Couple on the Floor", "1975", "Irving Daine, Johnny Durrill"],
    ["Only Forever", "1940 (radio)", "Johnny Burke, James Monaco"],
    ["Only One to a Customer", "1986", "Carolyn Leigh, Jule Styne"],
    ["Only the Lonely", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    ["Opening Theme", "1940 (radio)", "unknown"],
    ["Orange", "1956", "Nelson Riddle"],
    ["Our Love", "1939", "Buddy Bernier, Robert Emmerich, Larry Clinton"],
    ["Our Love Affair", "1940", "Roger Freed, Roger Edens"],
    ["Our Town", "1955", "Sammy Cahn, Jimmy Van Heusen"],
    ["Out Beyond the Window (spoken)", "1969", "Rod McKuen"],
    ["Out of Nowhere", "1942 (radio)", "Johnny Green, Edward Heyman"],
    ["Over the Rainbow", "1945", "Harold Arlen, Yip Harburg"],
    ["Pale Moon", "1941", "Frederic Knight Logan, Jesse G. M. Glick"],
    ["Paper Doll", "1961", "Johnny S. Black"],
    ["Paradise", "1945", "Nacio Herb Brown, Gordon Clifford"],
    ["Pass Me By", "1964", "Cy Coleman, Carolyn Leigh"],
    ["Peachtree Street", "1950", "Jimmy Saunders, Frank Sinatra, Leni Mason"],
    ["Pennies from Heaven", "1956, 1962", "Johnny Burke, Arthur Johnston"],
    ["People Will Say We're in Love", "1943", "Oscar Hammerstein II, Richard Rodgers"],
    ["Pick Yourself Up", "1962", "Dorothy Fields, Jerome Kern"],
    ["Please Be Kind", "1962", "Sammy Cahn, Saul Chaplin"],
    ["Please Don't Talk About Me When I'm Gone", "1961", "Sidney Clare, Sam H. Stept"],
    ["Pocketful of Miracles", "1961", "Sammy Cahn, Jimmy Van Heusen"],
    ["Poinciana", "1946, 1947", "Buddy Bernier, Nat Simon"],
    ["Polka Dots and Moonbeams", "1940, 1961", "Johnny Burke, Jimmy Van Heusen"],
    ["Poor Butterfly", "1967", "John Golden, Raymond Hubbell"],
    ["Poor You", "1942", "Yip Harburg, Burton Lane"],
    ["Prairie Night", "1941 (radio)", "unknown"],
    ["Pretty Colors", "1968", "Al Gorgoni, Chip Taylor"],
    ["A Pretty Girl is Like a Melody", "1942 (radio)", "Irving Berlin"],
    ["Prisoner of Love", "1961", "Russ Columbo, Clarence Gaskill, Leo Robin"],
    ["P.S. I Love You", "1956", "Gordon Jenkins, Johnny Mercer"],
    ["Purple", "1956", "Billy May"],
    [
        "Put Your Dreams Away (For Another Day)",
        "1945, 1957, 1963",
        "Ruth Lowe, Paul Mann, Stephan Weiss",
    ],
    ["Quiet Nights of Quiet Stars", "1967", "Antonio Carlos Jobim, Gene Lees"],
    ["Rain (Falling From The Skies)", "1953", "Gunther Finlay, Robert Mellin"],
    ["Rain in My Heart", "1968", "Victoria Pike, Teddy Randazzo"],
    ["Reaching for the Moon", "1965", "Irving Berlin"],
    ["Red", "1956", "André Previn"],
    ["Remember", "1962, 1978", "Irving Berlin"],
    ["Remember Me in Your Dreams", "1950", "Hal David, Morty Nevins"],
    ["The Right Girl for Me", "1949", "Betty Comden, Roger Edens, Adolph Green"],
    ["Ring-a-Ding-Ding!", "1960", "Sammy Cahn, Jimmy Van Heusen"],
    ["River Stay 'Way from My Door", "1960", "Matt Dixon, Harry M. Woods"],
    ["Roses of Picardy", "1962", "Frederic Weatherly, Haydn Wood"],
    [
        "The Saddest Thing of All",
        "1974, 1975",
        "Pierre Leroyer, Michel Legrand, Edward Ruault, Carl Sigman",
    ],
    ["Same Old Saturday Night", "1955", "Sammy Cahn, Frank Reardon"],
    ["Same Old Song and Dance", "1958", "Sammy Cahn, Jimmy Van Heusen, Bobby Worth"],
    ["Sand and Sea", "1966", "Gilbert Bécaud, Mack David, Maurice Vidalin"],
    ["Santa Claus Is Coming to Town", "1947", "John Frederick Coots, Haven Gillespie"],
    ["Satisfy Me One More Time", "1974", "Floyd Huddleston"],
    [
        "Saturday Night (Is the Loneliest Night of the Week)",
        "1944, 1958",
        "Sammy Cahn, Jule Styne",
    ],
    ["Say Hello!", "1981", "Richard Behrke, Sammy Cahn"],
    ["Say It", "1940", "Jimmy McHugh, Frank Loesser"],
    ["Searching", "1982, 1983", "Sammy Cahn, Jule Styne"],
    ["The Sea Song", "1954", "Dorothy Fields, Arthur Schwartz"],
    ["The Second Time Around", "1960, 1963,", "Sammy Cahn, Jimmy Van Heusen"],
    ["Secret Love", "1964", "Sammy Fain, Paul Francis Webster"],
    ["See the Show Again", "1994", "Barry Manilow, Adrienne Anderson"],
    ["Send in the Clowns", "1973, 1976", "Stephen Sondheim"],
    ["Senorita (I Offer You the Moon)", "1947", "Nacio Herb Brown, Edward Heyman"],
    ["Sentimental Baby", "1960", "Alan Bergman, Marilyn Bergman, Lew Spence"],
    ["Sentimental Journey", "1961", "Les Brown, Arthur Green, Ben Homer"],
    ["September in the Rain", "1960", "Al Dubin, Harry Warren"],
    ["The September of My Years", "1965", "Sammy Cahn, Jimmy Van Heusen"],
    ["September Song", "1946, 1961, 1965", "Maxwell Anderson, Kurt Weill"],
    ["Serenade in Blue", "1962", "Mack Gordon, Harry Warren"],
    ["Shadows on the Sand", "1940", "Stanley Adams, Will Grosz"],
    ["The Shadow of Your Smile", "1966", "Johnny Mandel, Paul Francis Webster"],
    ["Shake Down the Stars", "1940", "Eddie DeLange, Jimmy Van Heusen"],
    ["She Says", "1969", "Bob Gaudio, Jake Holmes"],
    ["Sheila", "1950", "Christopher R. Hayward, Frank Sinatra, Robert B. Staver"],
    ["She's Funny That Way", "1944, 1960", "Neil Moret, Richard A. Whiting"],
    ["Should I?", "1950, 1960", "Arthur Freed, Nacio Herb Brown"],
    ["Side by Side", "1957 (television), 1988 (live recording)", "Harry M. Woods"],
    ["Silent Night", "1945, 1957, 1991", "Traditional"],
    ["Silver", "1956", "Elmer Bernstein"],
    ["Since Marie Has Left Paree", "1964", "Hy Glaser, Jerry Solomon"],
    ["The Single Man", "1969", "Rod McKuen"],
    ["A Sinner Kissed an Angel", "1941", "Mack David, Larry Shayne"],
    ["The Sky Fell Down", "1940", "Louis Alter, Edward Heyman"],
    ["Sleep Warm", "1958", "Alan Bergman, Marilyn Bergman, Lew Spence"],
    [
        "Sleepy Time Gal",
        "1958",
        "Joseph R. Alden, Raymond B. Egan, Ange Lorenzo, Richard A. Whiting",
    ],
    ["On a Slow Boat to China", "1957 (television)", "Frank Loesser"],
    ["Slow Dance", "1945", "Alec Wilder"],
    ["Speak Low", "1943-8", "Ogden Nash, Kurt Weill"],
    ["Snootie Little Cutie", "1942", "Bobby Troup"],
    ["So Far", "1947", "Oscar Hammerstein II, Richard Rodgers"],
    ["So in Love", "1963", "Cole Porter"],
    ["So Long, My Love", "1957", "Sammy Cahn, Lew Spence"],
    ["So They Tell Me", "1946", "J. Gale, Arthur Kent, Harold Mott"],
    ["So You're the One", "1941 (radio)", "unknown"],
    ["Softly As I Leave You", "1964", "Giorgio Calabrese, Tony De Vita, Hal Shaper."],
    ["Soliloquy", "1946, 1955, 1963", "Oscar Hammerstein II, Richard Rodgers"],
    [
        "Some Enchanted Evening",
        "1949, 1963, 1967",
        "Oscar Hammerstein II, Richard Rodgers",
    ],
    [
        "Some of Your Sweetness (Got into My Heart)",
        "1940 (radio)",
        "G. Clayborn, J. Clayborn",
    ],
    ["Some Other Time (I Could Resist You)", "1944", "Sammy Cahn, Jule Styne"],
    ["Some Traveling Music (spoken)", "1969", "Rod McKuen"],
    ["Somebody Loves Me", "1940", "Buddy DeSylva, George Gershwin, Ballard MacDonald"],
    [
        "Someone to Light Up My Life",
        "1969",
        "Antonio Carlos Jobim, Gene Lees, Vinícius de Moraes",
    ],
    ["Someone To Watch Over Me", "1945, 1954", "George Gershwin, Ira Gershwin"],
    ["Somethin' Stupid", "1967", "Carson Parks"],
    ["Something", "1970, 1979", "George Harrison"],
    ["Something Old, Something New", "1946", "Ramey Idriss, George Tibbles"],
    [
        "Something Wonderful 	1957, 1962 	Oscar Hammerstein II, Richard Rodgers, Something Wonderful Happens in Summer",
        "1956, 1957",
        "Joe Bushkin, John DeVries",
    ],
    ["Something's Gotta Give", "1958", "Johnny Mercer"],
    ["Somewhere a Voice is Calling", "1942", "Eileen Newton, Arthur F. Tate"],
    ["Somewhere Along the Way", "1961", "Kurt Adams, Sammy Gallop"],
    ["Somewhere in the Night", "1946", "Mack Gordon, Josef Myrow"],
    ["Somewhere in Your Heart", "1964", "Russell Faith, Clarence Keltner"],
    ["Somewhere My Love (Lara's Theme)", "1966", "Maurice Jarre, Paul Francis Webster"],
    [
        "The Song is Ended (but the Melody Lingers On)",
        "1962",
        "Irving Berlin, Beda Loehner",
    ],
    [
        "The Song Is You",
        "1942, 1946, 1947, 1958, 1979",
        "Oscar Hammerstein II, Jerome Kern",
    ],
    ["Song of the Sabia", "1969", "Chico Buarque, Norman Gimbel, Antonio Carlos Jobim"],
    ["Song Sung Blue", "1979", "Neil Diamond"],
    ["Song Without Words", "1979", "Gordon Jenkins"],
    ["The Song's Gotta Come from the Heart", "1946 (film)", "Sammy Cahn, Jule Styne"],
    ["Sonny Boy", "1944 (radio)", "Lew Brown, Buddy DeSylva, Ray Henderson, Al Jolson"],
    ["Sorry", "1949", "Buddy Pepper, Richard A. Whiting"],
    ["South of the Border", "1953", "Michael Carr, Jimmy Kennedy"],
    ["South - To a Warmer Place", "1981", "Loonis McGlohon, Alec Wilder"],
    ["S'posin'", "1947, 1960", "Paul Denniker, Andy Razaf"],
    ["Spring Is Here", "1947, 1958", "Lorenz Hart, Richard Rodgers"],
    ["Star", "1968", "Sammy Cahn, Jimmy Van Heusen"],
    ["Stardust", "1940, 1961", "Hoagy Carmichael, Mitchell Parish"],
    ["Stargazer", "1976", "Neil Diamond"],
    ["Stars Fell on Alabama", "1956", "Mitchell Parish, Frank Perkins"],
    [
        "Stars in Your Eyes",
        "1945",
        "Mort Greene, Ricardo López Méndez, Gabriel Ruiz (composer)",
    ],
    [
        "Stay with Me (Main Theme from The Cardinal)",
        "1963",
        "Carolyn Leigh, Jerome Moross",
    ],
    ["The Stars Will Remember", "1947", "Don Pelosi, Leo Towers"],
    ["Stella by Starlight", "1947", "Ned Washington, Victor Young"],
    [
        "Stompin' at the Savoy",
        "1967 (television)",
        "Benny Goodman, Edgar Sampson, Chick Webb",
    ],
    ["Stormy Weather", "1944, 1959, 1984", "Harold Arlen, Ted Koehler"],
    ["Strange Music", "1946, 1947", "Edvard Grieg"],
    [
        "Strangers in the Night",
        "1966",
        "Bert Kaempfert, Charles Singleton, Eddie Snyder",
    ],
    ["Street of Dreams", "1942, 1979", "Sam M. Lewis, Victor Young"],
    ["(On the Island of) Stromboli", "1949, 1964", "K. Lane, Taylor"],
    ["Style", "1964", "Sammy Cahn, Jimmy Van Heusen"],
    ["The Summer Knows", "1974", "Alan Bergman, Marilyn Bergman, Michel Legrand"],
    ["Summer Me, Winter Me", "1979", "Alan Bergman, Marilyn Bergman, Michel Legrand"],
    ["Summer Wind", "1966, 1993", "Heinz Meier, Johnny Mercer"],
    ["Sunday", "1954", "Chester Conn, Bennie Krueger, Ned Miller, Jule Styne"],
    ["Sunday, Monday or Always", "1943", "Johnny Burke, Jimmy Van Heusen"],
    ["Sunflower", "1948", "Mack David, Russ Morgan"],
    ["Sunny", "1967", "Bobby Hebb"],
    ["Sunrise in the Morning", "1970", "Paul Ryan"],
    ["Sunrise Over Taxco", "1941 (radio)", "Elliot, Pardue"],
    ["Sunshine Cake", "1949", "Johnny Burke, Jimmy Van Heusen"],
    ["The Sunshine of Your Smile", "1941", "Leonard Cooke, Lillian Ray"],
    ["Sure Thing", "1949", "Johnny Burke, Jimmy Van Heusen"],
    [
        "The Surrey with the Fringe on Top",
        "1945, 1980",
        "Oscar Hammerstein II, Richard Rodgers",
    ],
    ["Sweet and Lovely", "1983", "Gus Arnheim, Neil Moret, Harry Tobias"],
    ["Sweet Caroline", "1974", "Neil Diamond"],
    ["Sweet Chariot", "1963 (live recording)", "Duke Ellington, Irving Mills"],
    ["Sweet Lorraine", "1946, 1977", "Cliff Burwell, Mitchell Parish"],
    ["The Sweetheart of Sigma Chi", "1957 (radio)", "Bryan Stokes, F. Dudleigh Vernor"],
    ["Swinging on a Star", "1964", "Johnny Burke, Jimmy Van Heusen"],
    ["Swingin' Down the Lane", "1956", "Isham Jones, Gus Kahn"],
    ["Take a Chance", "1953", "David Raksin, Don Stanford"],
    ["Take Me", "1942, 1961", "Rube Bloom, Mack David"],
    ["Take Me Out to the Ball Game", "1946 (film)", "Jack Norworth, Albert Von Tilzer"],
    ["Take My Love", "1950", "Joel Herron, Frank Sinatra, Jack Wolf"],
    ["Take the A Train", "1965 (television)", "Billy Strayhorn"],
    ["Taking a Chance on Love", "1954", "Vernon Duke, John Latouche, Ted Fetter"],
    ["Talk to Me", "1959", "Eddie Snyder, Rudy Vallee, Stanley Kahan"],
    ["Talk to Me Baby", "1963", "Robert E. Dolan, Johnny Mercer"],
    ["Tammy", "1962", "Jay Livingston, Ray Evans"],
    ["Tangerine", "1962", "Johnny Mercer, Victor Schertzinger"],
    ["Tea for Two", "1946 (radio), 1947", "Irving Caesar, Vincent Youmans"],
    ["Teach Me Tonight", "1984", "Sammy Cahn, Gene De Paul"],
    ["Tell Her You Love Her", "1957", "Homer Denison, Hugh Halliday, Sol Parker"],
    ["Tell Her (You Love Her Each Day)", "1965", "Samuel Ward, Charles Watkins"],
    ["Tell Me at Midnight", "1940", "Clay A. Boland, Bickley Reichner"],
    ["Tenderly", "1980", "Walter Gross, Jack Lawrence"],
    ["Tennessee News Boy (The Newsboy Blues)", "1952", "Percy Faith, Dick Manning"],
    ["Thanks for the Memory", "1981", "Leo Robin, Ralph Rainger"],
    ["That Great Come and Get It Day", "1954 (film)", "Yip Harburg, Burton Lane"],
    ["That Lucky Old Sun", "1949", "Haven Gillespie, Beasley Smith"],
    ["That Old Black Magic", "1946, 1961, 1975", "Harold Arlen, Johnny Mercer"],
    ["That Old Feeling", "1947, 1960", "Lew Brown, Sammy Fain"],
    ["That's All", "1961", "Alan Brandt, Bob Haymes"],
    ["That's For Me", "1945", "Oscar Hammerstein II, Richard Rodgers"],
    ["That's How Much I Love You", "1946", "Eddy Arnold, Wally Fowler"],
    ["That's How It Goes", "1941 (radio)", "L. Martin, M. Gentile"],
    ["That's Life", "1966", "Kelly Gordon, Dean Kay"],
    ["That's What God Looks Like to Me", "1978, 1979", "Lois Irwin, Lan O'Kun"],
    ["Them There Eyes", "1982", "Maceo Pinkard, Doris Tauber, William Tracey"],
    ["Theme from New York, New York", "1979, 1993", "Fred Ebb, John Kander"],
    ["Theme and Variations", "1945", "Alec Wilder"],
    ["Then I'll Be Tired of You", "1957", "Yip Harburg, Arthur Schwartz"],
    ["Then Suddenly Love", "1964", "Roy Alfred, Paul Vance"],
    [
        "There Are Such Things",
        "1942, 1961",
        "Stanley Adams, Abel Baer, George W. Meyer",
    ],
    ["There But for You Go I", "1947", "Alan Jay Lerner, Frederick Loewe"],
    ["There Goes That Song Again", "1943", "Sammy Cahn, Jule Styne"],
    ["There I Go", "1941 (radio)", "Weiser, Hy Zaret"],
    ["There Used to Be a Ballpark", "1973", "Joe Raposo"],
    ["There Will Never Be Another You", "1961", "Mack Gordon, Harry Warren"],
    [
        "(There'll Be a) Hot Time in the Town of Berlin",
        "1943-8",
        "Joe Bushkin, John DeVries",
    ],
    ["There's a Flaw in My Flue", "1956", "Sammy Cahn, Jimmy Van Heusen"],
    [
        "There's a Long Long Trail",
        "1954 (radio), 1957 (television)",
        "Alonzo Elliot, Stoddard King",
    ],
    ["There's a Small Hotel", "1957", "Lorenz Hart, Richard Rodgers"],
    ["There's No Business Like Show Business", "1946 (radio)", "Irving Berlin"],
    ["There's No You", "1944, 1957", "Tom Adair, Hal Hopper"],
    [
        "There's Something Missing",
        "1950, 1951",
        "Rule, O'Brien, Bennie Benjamin, George David Weiss, Downey",
    ],
    ["These Boots Are Made for Walkin'", "1966 (television)", "Lee Hazlewood"],
    [
        "These Foolish Things (Remind Me of You)",
        "1945, 1961",
        "Eric Maschwitz, Jack Strachey",
    ],
    ["They All Laughed", "1979", "George Gershwin, Ira Gershwin"],
    ["They Came to Cordura", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    [
        "They Can't Take That Away from Me",
        "1953, 1962, 1993",
        "George Gershwin, Ira Gershwin",
    ],
    ["They Say It's Wonderful", "1946", "Irving Berlin"],
    [
        "The Things I Love",
        "1941 (radio)",
        "H. Barlow, L. Harris, Peter Ilich Tchaikovsky",
    ],
    ["The Things We Did Last Summer", "1946", "Sammy Cahn, Jule Styne"],
    [
        "This Can't Be Love",
        "1949 (radio), 1958 (television)",
        "Lorenz Hart, Richard Rodgers",
    ],
    [
        "This Happy Madness (Estrada Branca)",
        "1969",
        "Antonio Carlos Jobim, Gene Lees, Vinicius de Moraes",
    ],
    ["This Is All I Ask", "1965", "Gordon Jenkins"],
    ["This Is My Love", "1967", "James Harbert"],
    ["This Is My Song", "1967", "Charlie Chaplin"],
    ["This Is No Dream", "1939", "Benny Davis, Tommy Dorsey, Ted Shapiro"],
    ["This Is the Beginning of the End", "1940", "Mack Gordon"],
    ["This Is the Night", "1946", "Louis Bellin, Redd Evans"],
    [
        "This Love of Mine",
        "1941, 1955",
        "Barry Parker, Henry W. Sanicola, Frank Sinatra",
    ],
    ["This Nearly Was Mine", "1963", "Oscar Hammerstein II, Richard Rodgers"],
    ["This Town", "1967", "Lee Hazlewood"],
    ["This Was My Love", "1959", "Jim Harbert"],
    ["Three Coins in the Fountain", "1954, 1964", "Sammy Cahn, Jule Styne"],
    [
        "Tie a Yellow Ribbon Round the Ole Oak Tree",
        "1974",
        "L. Russell Brown, Irwin Levine",
    ],
    ["Till We Meet Again", "1954 (radio)", "Raymond B. Egan, Richard A. Whiting"],
    ["Time After Time", "1946, 1957", "Sammy Cahn, Jule Styne"],
    ["Tina", "1960", "Sammy Cahn, Jimmy Van Heusen"],
    ["To Love a Child", "1981", "Hal David, Joe Raposo"],
    ["To Love and Be Loved", "1958", "Sammy Cahn, Jimmy Van Heusen"],
    ["Together", "1962", "Lew Brown, Buddy De Sylva, Ray Henderson"],
    ["Tony Rome", "1967 (television)", "Lee Hazlewood"],
    [
        "Too Close for Comfort",
        "1958",
        "Jerry Bock, Larry Holofcener, George David Weiss",
    ],
    ["Too Marvelous for Words", "1956", "Johnny Mercer, Richard A. Whiting"],
    ["Too Romantic", "1940", "Johnny Burke, James Monaco"],
    ["Trade Winds", "1940", "Cliff Friend, Charles Tobias"],
    ["The Train", "1969", "Bob Gaudio, Jake Holmes"],
    ["Triste", "1969", "Antonio Carlos Jobim"],
    [
        "Try a Little Tenderness",
        "1945, 1960",
        "Jimmy Campbell and Reg Connelly, Harry M. Woods",
    ],
    ["The Twelve Days Of Christmas", "1968", "Traditional"],
    [
        "Twin Soliloquies (Wonder How it Feels)",
        "1963",
        "Oscar Hammerstein II, Richard Rodgers",
    ],
    ["Two Hearts are Better Than One", "1946", "Oscar Hammerstein II, Jerome Kern"],
    ["Two Hearts, Two Kisses (Make One Love)", "1955", "Henry Stone, Otis Williams"],
    ["Two in Love", "1941", "Meredith Willson"],
    [
        "Until the Real Thing Comes Along",
        "1984",
        "Sammy Cahn, Saul Chaplin, L.E. Freeman",
    ],
    ["Up, Up and Away", "1967 (television)", "Jimmy Webb"],
    ["Violets for Your Furs", "1941, 1953", "Tom Adair, Matt Dennis"],
    ["The Very Thought of You", "1962", "Ray Noble"],
    ["Volare", "1980 (live recording)", "Franco Migliacci, Domenico Modugno"],
    ["Wait for Me (Johnny Concho Theme)", "1956", "Nelson Riddle, Dok Stanford"],
    ["Wait Till You See Her", "1956", "Lorenz Hart, Richard Rodgers"],
    ["Walk Away", "1973", "Elmer Bernstein, Carolyn Leigh"],
    ["Walking Down to Washington", "1961", "unknown"],
    ["Walkin' in the Sunshine", "1952", "Bob Merrill"],
    ["Wandering", "1968", "Gayle Caldwell"],
    [
        "Was the Last Time I Saw You (The Last Time)",
        "1943-8",
        "Marjorie Goetschius, Edna Osser",
    ],
    ["Watch What Happens", "1969", "Jacques Demy, Norman Gimbel, Michel Legrand"],
    [
        "Drinking Water (Agua de Beber)",
        "1969",
        "Antonio Carlos Jobim, Norman Gimbel, Vinicius de Moraes",
    ],
    ["Watertown", "1969", "Bob Gaudio, Jake Holmes"],
    ["Wave", "1969", "Antonio Carlos Jobim"],
    ["The Way You Look Tonight", "1964", "Dorothy Fields, Jerome Kern"],
    ["We Just Couldn't Say Goodbye", "1947", "Harry M. Woods"],
    ["We Kiss in a Shadow", "1951", "Oscar Hammerstein II, Richard Rodgers"],
    ["We Open in Venice", "1963", "Cole Porter"],
    [
        "We Three (My Echo, My Shadow, and Me)",
        "1940",
        "Nelson Cogane, Sammy Mysels, Dick Robertson",
    ],
    ["We Wish You the Merriest", "1964", "Les Brown"],
    ["The Wedding of Lili Marlene", "1949", "Tommie Connor, Johnny Reine"],
    ["Weep They Will", "1955", "Bill Carey, Carl T. Fischer"],
    ["Well, Did You Evah!", "1956", "Cole Porter"],
    ["We'll Be Together Again", "1956", "Carl T. Fischer, Frankie Laine"],
    ["We'll Gather Lilacs in the Spring", "1962", "Ivor Novello"],
    ["We'll Meet Again", "1962", "Hughie Charles, Ross Parker"],
    ["We're Glad That We're Italian", "1959 (live recording)", "Sammy Cahn"],
    ["We're Just a Kiss Apart", "1949", "Leo Robin, Jule Styne"],
    ["What a Funny Girl (You Used to Be)", "1969", "Bob Gaudio, Jake Holmes"],
    [
        "What Are You Doing the Rest of Your Life?",
        "1974",
        "Alan Bergman, Marilyn Bergman, Michel Legrand",
    ],
    ["What Do I Care for a Dame?", "1957", "Lorenz Hart, Richard Rodgers"],
    ["What Is This Thing Called Love?", "1955", "Cole Porter"],
    ["What Makes the Sunset?", "1944", "Sammy Cahn, Jule Styne"],
    ["What Now My Love", "1966, 1993", "Gilbert Bécaud, Pierre Leroyer, Carl Sigman"],
    ["What Time Does the Next Miracle Leave?", "1979", "Gordon Jenkins"],
    ["Whatever Happened to Christmas?", "1968", "Jimmy Webb"],
    ["What'll I Do", "1947, 1962", "Irving Berlin"],
    ["What's New?", "1958", "Johnny Burke, Bob Haggart"],
    ["What's Now is Now", "1969", "Bob Gaudio, Jake Holmes"],
    ["When I Lost You", "1962", "Irving Berlin"],
    ["When Daylight Dawns", "1941 (radio)", "Bea Huberdo"],
    [
        "When I Stop Loving You 	1954 	Cates, Copeland, Green, When I Take My Sugar to Tea",
        "1960",
        "Sammy Fain, Irving Kahal, Pierre Norman",
    ],
    ["When I'm Not Near the Girl I Love", "1963", "Yip Harburg, Burton Lane"],
    ["When is Sometime?", "1947", "Johnny Burke, Jimmy Van Heusen"],
    ["When Joanna Loved Me", "1987 (live recording)", "Jack Segal, Robert Wells"],
    ["When Love Comes Again", "1941", "Gerry Deane, Lou Halmy"],
    ["When No One Cares", "1959", "Sammy Cahn, Jimmy Van Heusen"],
    ["When Sleepy Stars Begin to Fall", "1941 (radio)", "Sibyl Allen"],
    ["When Somebody Loves You", "1965", "Sammy Cahn, Jimmy Van Heusen"],
    ["When the Sun Goes Down", "1950", "Walter O'Keefe, Irvine C. Orton"],
    ["When the Wind Was Green", "1965", "Henry Stinson"],
    [
        "When the World Was Young",
        "1961",
        "Johnny Mercer, M. Philippe-Gerard, Angele Marie T. Vannier",
    ],
    ["When You Awake", "1940, 1947", "Henry Nemo"],
    ["When Your Lover Has Gone", "1944, 1955", "Einar Aaron Swan"],
    [
        "When You're Smiling 	1950, 1960 	Mark Fisher, Joe Goodwin, Larry Shay, Where Are You?",
        "1957",
        "Harold Adamson, Jimmy McHugh",
    ],
    ["Where Do You Go?", "1959", "Arnold Sundgaard, Alec Wilder"],
    ["Where Do You Keep Your Heart?", "1940", "Fred E. Ahlert, Al Stillman"],
    ["Where is the One?", "1947, 1957", "Edwin Finckel, Alec Wilder"],
    ["Where or When", "1945, 1958, 1994", "Lorenz Hart, Richard Rodgers"],
    ["While the Angelus Was Ringing", "1948", "Jean Villard, Dick Manning"],
    ["Whispering", "1940", "Richard Coburn, Vincent Rose, John Schonberger"],
    ["White", "1956", "Victor Young"],
    ["White Christmas", "1944, 1947, 1954", "Irving Berlin"],
    ["Who", "1940 (radio)", "Oscar Hammerstein II, Otto Harbach, Jerome Kern"],
    ["Who Told You I Cared?", "1939", "Bert Reisfeld, George Whiting"],
    ["Who Wants to be a Millionaire?", "1956", "Cole Porter"],
    ["Why Am I Still Dreaming?", "1940 (radio)", "unknown"],
    ["Why Can't You Behave?", "1948", "Cole Porter"],
    ["Why Remind Me?", "1949", "Doris Tauber, Sis Willner"],
    ["Why Should I Cry Over You?", "1953", "Chester Conn, Ned Miller"],
    ["Why Shouldn't I?", "1945", "Cole Porter"],
    ["Why Shouldn't it Happen to Us?", "1946", "Mann Holiner, Alberta Nichols"],
    ["Why Try to Change Me Now?", "1952, 1959", "Cy Coleman, Joseph A. McCarthy"],
    ["Why Was I Born?", "1947", "Oscar Hammerstein II, Jerome Kern"],
    ["Willow Weep for Me", "1958", "Ann Ronell"],
    ["Winchester Cathedral", "1966", "Geoff Stephens"],
    ["Winners", "1973", "Joe Raposo"],
    ["Winter Wonderland", "1949", "Felix Bernard, Richard B. Smith"],
    ["Wishing Will Make It So", "1939", "Buddy DeSylva"],
    ["Witchcraft", "1957, 1963, 1993", "Cy Coleman, Carolyn Leigh"],
    ["With Every Breath I Take", "1956", "Ralph Rainger, Leo Robin"],
    ["Without a Song", "1941, 1961", "Edward Eliscu, Billy Rose, Vincent Youmans"],
    ["Wives and Lovers", "1964", "Burt Bacharach, Hal David"],
    ["The World Is in My Arms", "1940", "Yip Harburg, Burton Lane"],
    ["World War None", "1979", "Gordon Jenkins"],
    [
        "The World We Knew (Over and Over)",
        "1967",
        "Bert Kaempfert, Herbert Rehbein, Carl Sigman",
    ],
    ["Wrap Your Troubles In Dreams", "1954", "Harry Barris, Ted Koehler, Billy Moll"],
    ["Ya Better Stop", "1953", "Cliff Ferre, Mark McIntyre"],
    ["Yearning (Just For You)", "1940", "Joe Burke, Benny Davis"],
    ["Yellow", "1956", "Jeff Alexander"],
    ["Yellow Days", "1967", "Alan Bernstein, Alarcon Carrillo"],
    ["Yes Indeed", "1945 (radio), 1958 (TV), 1961", "Sy Oliver"],
    ["Yes Sir, That's My Baby", "1966", "Walter Donaldson, Gus Kahn"],
    ["Yesterday", "1969", "John Lennon, Paul McCartney"],
    ["Yesterdays", "1961", "Otto Harbach, Jerome Kern"],
    ["You and I", "1941", "Meredith Willson"],
    ["You and Me", "1978, 1979", "Peter Allen, Carole Bayer Sager"],
    ["You and the Night and the Music", "1960", "Howard Dietz, Arthur Schwartz"],
    ["You Are My Sunshine", "1944 (radio)", "Jimmie Davis, Charles Mitchell"],
    ["You Are the Sunshine of My Life", "1974, 1975", "Stevie Wonder"],
    ["You Are There", "1967", "Harry Sukman, Paul Francis Webster"],
    ["You Are Too Beautiful", "1945", "Lorenz Hart, Richard Rodgers"],
    [
        "You Brought a New Kind of Love to Me",
        "1956, 1963",
        "Pierre Connor, Sammy Fain, Irving Kahal",
    ],
    ["You Can Take My Word for It, Baby", "1946", "Ticker Freeman, Irving Taylor"],
    ["You Cast a Spell Over Me", "1940 (radio)", "unknown"],
    ["You Don't Remind Me", "1950", "Cole Porter"],
    ["You Do Something to Me", "1950, 1960", "Cole Porter"],
    ["You Forgot All the Words", "1955", "Bernie Wayne, E.H. Jay"],
    ["You Go to My Head", "1945, 1960", "J. Fred Coots, Haven Gillespie"],
    ["You Got the Best of Me", "1941", "Joy Font"],
    ["You Lucky People, You", "1941", "Johnny Burke, Jimmy Van Heusen"],
    ["You Make Me Feel So Young", "1956, 1993", "Mack Gordon, Josef Myrow"],
    ["You Might Have Belonged to Another", "1941", "P. West, L. Harmon"],
    [
        "You Must Believe In Spring",
        "1982",
        "Alan Bergman, Marilyn Bergman, Jacques Demy, Michel Legrand",
    ],
    [
        "You Must Have Been a Beautiful Baby",
        "1959 (television)",
        "Johnny Mercer, Harry Warren",
    ],
    ["You, My Love", "1954", "Mack Gordon, Jimmy Van Heusen"],
    ["You Never Had It So Good", "1964", "Sammy Cahn, Jimmy Van Heusen"],
    ["You Really Fill the Bill", "1940", "Warren Hull"],
    [
        "You Turned My World Around",
        "1974",
        "Kim Carnes, Bert Kaempfert, Herbert Rehbein, David Ellingson",
    ],
    ["You Walk By", "1940 (radio)", "unknown"],
    ["You Will Be My Music", "1973", "Joe Raposo"],
    ["You'd Be So Easy to Love", "1960", "Cole Porter"],
    ["You'd Be So Nice to Come Home To", "1956", "Cole Porter"],
    ["You'll Always Be the One I Love", "1957", "Sunny Skylar, Ticker Freeman"],
    ["You'll Get Yours", "1955", "Jimmy Van Heusen, Don Stanford"],
    ["You'll Know it When it Happens", "1946", "J.J. Loeb, Carmen Lombardo"],
    ["You'll Never Know", "1943", "Mack Gordon, Harry Warren"],
    ["You'll Never Walk Alone", "1945, 1963", "Oscar Hammerstein II, Richard Rodgers"],
    ["Young At Heart", "1953, 1963", "Carolyn Leigh, Johnny Richards"],
    ["Younger Than Springtime", "1967", "Oscar Hammerstein II, Richard Rodgers"],
    ["Your Cheatin' Heart", "1952", "Hank Williams"],
    ["Your Love for Me", "1956", "Sol Parker"],
    [
        "You're a Lucky Fellow, Mr. Smith",
        "1964",
        "Francis Burke, Hughie Prince, Don Raye",
    ],
    [
        "You're Breaking My Heart (All Over Again)",
        "1940",
        "James Cavanaugh, Arthur Altman, John Redmond",
    ],
    [
        "You're Cheatin' Yourself (If You're Cheatin' on Me)",
        "1957",
        "Al Hoffman, Dick Manning",
    ],
    ["You're Driving Me Crazy", "1966", "Walter Donaldson"],
    ["You're Getting to Be a Habit With Me", "1956", "Al Dubin, Harry Warren"],
    ["You're Gonna Hear from Me", "1966", "André Previn, Dory Previn"],
    ["You're Lonely and I'm Lonely", "1940", "Irving Berlin"],
    ["You're My Girl", "1947", "Sammy Cahn, Jule Styne"],
    [
        "You're Nobody till Somebody Loves You",
        "1961",
        "James Cavanaugh, Russ Morgan, Larry Stock",
    ],
    ["You're Part of My Heart", "1941 (radio)", "Virginia Sloane"],
    ["You're Sensational", "1956", "Cole Porter"],
    ["You're Stepping on My Toes", "1941 (radio)", "Robert Terry"],
    [
        "You're So Right (For What's Wrong in My Life)",
        "1973",
        "Victoria Pike, Teddy Randazzo, Roger Joyce",
    ],
    ["You're the One (For Me)", "1951", "Ned Washington, Victor Young"],
    ["You're the Top", "1944 (radio)", "Cole Porter"],
    [
        "Yours Is My Heart Alone",
        "1940",
        "Ludwig Herzer, Franz Lehár, Fritz Löhner-Beda",
    ],
    ["Zing! Went the Strings of My Heart", "1960", "James F. Hanley"],
    ["Zip-A-Dee-Doo-Dah", "1951", "Ray Gilbert"],
];

module.exports = {
	frank_sinatra_songs
};
